// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: runthread/v1/runthread.proto

package runthreadv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExperienceLevel int32

const (
	ExperienceLevel_EXPERIENCE_LEVEL_UNSPECIFIED  ExperienceLevel = 0
	ExperienceLevel_EXPERIENCE_LEVEL_BEGINNER     ExperienceLevel = 1
	ExperienceLevel_EXPERIENCE_LEVEL_INTERMEDIATE ExperienceLevel = 2
	ExperienceLevel_EXPERIENCE_LEVEL_ADVANCED     ExperienceLevel = 3
)

// Enum value maps for ExperienceLevel.
var (
	ExperienceLevel_name = map[int32]string{
		0: "EXPERIENCE_LEVEL_UNSPECIFIED",
		1: "EXPERIENCE_LEVEL_BEGINNER",
		2: "EXPERIENCE_LEVEL_INTERMEDIATE",
		3: "EXPERIENCE_LEVEL_ADVANCED",
	}
	ExperienceLevel_value = map[string]int32{
		"EXPERIENCE_LEVEL_UNSPECIFIED":  0,
		"EXPERIENCE_LEVEL_BEGINNER":     1,
		"EXPERIENCE_LEVEL_INTERMEDIATE": 2,
		"EXPERIENCE_LEVEL_ADVANCED":     3,
	}
)

func (x ExperienceLevel) Enum() *ExperienceLevel {
	p := new(ExperienceLevel)
	*p = x
	return p
}

func (x ExperienceLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExperienceLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_runthread_v1_runthread_proto_enumTypes[0].Descriptor()
}

func (ExperienceLevel) Type() protoreflect.EnumType {
	return &file_runthread_v1_runthread_proto_enumTypes[0]
}

func (x ExperienceLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExperienceLevel.Descriptor instead.
func (ExperienceLevel) EnumDescriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{0}
}

type Provider int32

const (
	Provider_PROVIDER_UNSPECIFIED Provider = 0
	Provider_PROVIDER_GARMIN      Provider = 1
	Provider_PROVIDER_STRAVA      Provider = 2
)

// Enum value maps for Provider.
var (
	Provider_name = map[int32]string{
		0: "PROVIDER_UNSPECIFIED",
		1: "PROVIDER_GARMIN",
		2: "PROVIDER_STRAVA",
	}
	Provider_value = map[string]int32{
		"PROVIDER_UNSPECIFIED": 0,
		"PROVIDER_GARMIN":      1,
		"PROVIDER_STRAVA":      2,
	}
)

func (x Provider) Enum() *Provider {
	p := new(Provider)
	*p = x
	return p
}

func (x Provider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Provider) Descriptor() protoreflect.EnumDescriptor {
	return file_runthread_v1_runthread_proto_enumTypes[1].Descriptor()
}

func (Provider) Type() protoreflect.EnumType {
	return &file_runthread_v1_runthread_proto_enumTypes[1]
}

func (x Provider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Provider.Descriptor instead.
func (Provider) EnumDescriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{1}
}

type ProviderConnectionStatus int32

const (
	ProviderConnectionStatus_PROVIDER_CONNECTION_STATUS_UNSPECIFIED  ProviderConnectionStatus = 0
	ProviderConnectionStatus_PROVIDER_CONNECTION_STATUS_PENDING      ProviderConnectionStatus = 1
	ProviderConnectionStatus_PROVIDER_CONNECTION_STATUS_CONNECTED    ProviderConnectionStatus = 2
	ProviderConnectionStatus_PROVIDER_CONNECTION_STATUS_SYNCING      ProviderConnectionStatus = 3
	ProviderConnectionStatus_PROVIDER_CONNECTION_STATUS_ERROR        ProviderConnectionStatus = 4
	ProviderConnectionStatus_PROVIDER_CONNECTION_STATUS_DISCONNECTED ProviderConnectionStatus = 5
)

// Enum value maps for ProviderConnectionStatus.
var (
	ProviderConnectionStatus_name = map[int32]string{
		0: "PROVIDER_CONNECTION_STATUS_UNSPECIFIED",
		1: "PROVIDER_CONNECTION_STATUS_PENDING",
		2: "PROVIDER_CONNECTION_STATUS_CONNECTED",
		3: "PROVIDER_CONNECTION_STATUS_SYNCING",
		4: "PROVIDER_CONNECTION_STATUS_ERROR",
		5: "PROVIDER_CONNECTION_STATUS_DISCONNECTED",
	}
	ProviderConnectionStatus_value = map[string]int32{
		"PROVIDER_CONNECTION_STATUS_UNSPECIFIED":  0,
		"PROVIDER_CONNECTION_STATUS_PENDING":      1,
		"PROVIDER_CONNECTION_STATUS_CONNECTED":    2,
		"PROVIDER_CONNECTION_STATUS_SYNCING":      3,
		"PROVIDER_CONNECTION_STATUS_ERROR":        4,
		"PROVIDER_CONNECTION_STATUS_DISCONNECTED": 5,
	}
)

func (x ProviderConnectionStatus) Enum() *ProviderConnectionStatus {
	p := new(ProviderConnectionStatus)
	*p = x
	return p
}

func (x ProviderConnectionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderConnectionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_runthread_v1_runthread_proto_enumTypes[2].Descriptor()
}

func (ProviderConnectionStatus) Type() protoreflect.EnumType {
	return &file_runthread_v1_runthread_proto_enumTypes[2]
}

func (x ProviderConnectionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderConnectionStatus.Descriptor instead.
func (ProviderConnectionStatus) EnumDescriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{2}
}

type GoalType int32

const (
	GoalType_GOAL_TYPE_UNSPECIFIED     GoalType = 0
	GoalType_GOAL_TYPE_GENERAL_FITNESS GoalType = 1
	GoalType_GOAL_TYPE_RACE            GoalType = 2
	GoalType_GOAL_TYPE_DISTANCE        GoalType = 3
	GoalType_GOAL_TYPE_TIME            GoalType = 4
)

// Enum value maps for GoalType.
var (
	GoalType_name = map[int32]string{
		0: "GOAL_TYPE_UNSPECIFIED",
		1: "GOAL_TYPE_GENERAL_FITNESS",
		2: "GOAL_TYPE_RACE",
		3: "GOAL_TYPE_DISTANCE",
		4: "GOAL_TYPE_TIME",
	}
	GoalType_value = map[string]int32{
		"GOAL_TYPE_UNSPECIFIED":     0,
		"GOAL_TYPE_GENERAL_FITNESS": 1,
		"GOAL_TYPE_RACE":            2,
		"GOAL_TYPE_DISTANCE":        3,
		"GOAL_TYPE_TIME":            4,
	}
)

func (x GoalType) Enum() *GoalType {
	p := new(GoalType)
	*p = x
	return p
}

func (x GoalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GoalType) Descriptor() protoreflect.EnumDescriptor {
	return file_runthread_v1_runthread_proto_enumTypes[3].Descriptor()
}

func (GoalType) Type() protoreflect.EnumType {
	return &file_runthread_v1_runthread_proto_enumTypes[3]
}

func (x GoalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GoalType.Descriptor instead.
func (GoalType) EnumDescriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{3}
}

type WeekFocus int32

const (
	WeekFocus_WEEK_FOCUS_UNSPECIFIED WeekFocus = 0
	WeekFocus_WEEK_FOCUS_BASE        WeekFocus = 1
	WeekFocus_WEEK_FOCUS_BUILD       WeekFocus = 2
	WeekFocus_WEEK_FOCUS_RECOVERY    WeekFocus = 3
	WeekFocus_WEEK_FOCUS_PEAK        WeekFocus = 4
	WeekFocus_WEEK_FOCUS_TAPER       WeekFocus = 5
)

// Enum value maps for WeekFocus.
var (
	WeekFocus_name = map[int32]string{
		0: "WEEK_FOCUS_UNSPECIFIED",
		1: "WEEK_FOCUS_BASE",
		2: "WEEK_FOCUS_BUILD",
		3: "WEEK_FOCUS_RECOVERY",
		4: "WEEK_FOCUS_PEAK",
		5: "WEEK_FOCUS_TAPER",
	}
	WeekFocus_value = map[string]int32{
		"WEEK_FOCUS_UNSPECIFIED": 0,
		"WEEK_FOCUS_BASE":        1,
		"WEEK_FOCUS_BUILD":       2,
		"WEEK_FOCUS_RECOVERY":    3,
		"WEEK_FOCUS_PEAK":        4,
		"WEEK_FOCUS_TAPER":       5,
	}
)

func (x WeekFocus) Enum() *WeekFocus {
	p := new(WeekFocus)
	*p = x
	return p
}

func (x WeekFocus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WeekFocus) Descriptor() protoreflect.EnumDescriptor {
	return file_runthread_v1_runthread_proto_enumTypes[4].Descriptor()
}

func (WeekFocus) Type() protoreflect.EnumType {
	return &file_runthread_v1_runthread_proto_enumTypes[4]
}

func (x WeekFocus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WeekFocus.Descriptor instead.
func (WeekFocus) EnumDescriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{4}
}

type WorkoutType int32

const (
	WorkoutType_WORKOUT_TYPE_UNSPECIFIED WorkoutType = 0
	WorkoutType_WORKOUT_TYPE_EASY        WorkoutType = 1
	WorkoutType_WORKOUT_TYPE_LONG_RUN    WorkoutType = 2
	WorkoutType_WORKOUT_TYPE_WORKOUT     WorkoutType = 3
	WorkoutType_WORKOUT_TYPE_RECOVERY    WorkoutType = 4
	WorkoutType_WORKOUT_TYPE_RACE        WorkoutType = 5
	WorkoutType_WORKOUT_TYPE_REST        WorkoutType = 6
	WorkoutType_WORKOUT_TYPE_STRENGTH    WorkoutType = 7
)

// Enum value maps for WorkoutType.
var (
	WorkoutType_name = map[int32]string{
		0: "WORKOUT_TYPE_UNSPECIFIED",
		1: "WORKOUT_TYPE_EASY",
		2: "WORKOUT_TYPE_LONG_RUN",
		3: "WORKOUT_TYPE_WORKOUT",
		4: "WORKOUT_TYPE_RECOVERY",
		5: "WORKOUT_TYPE_RACE",
		6: "WORKOUT_TYPE_REST",
		7: "WORKOUT_TYPE_STRENGTH",
	}
	WorkoutType_value = map[string]int32{
		"WORKOUT_TYPE_UNSPECIFIED": 0,
		"WORKOUT_TYPE_EASY":        1,
		"WORKOUT_TYPE_LONG_RUN":    2,
		"WORKOUT_TYPE_WORKOUT":     3,
		"WORKOUT_TYPE_RECOVERY":    4,
		"WORKOUT_TYPE_RACE":        5,
		"WORKOUT_TYPE_REST":        6,
		"WORKOUT_TYPE_STRENGTH":    7,
	}
)

func (x WorkoutType) Enum() *WorkoutType {
	p := new(WorkoutType)
	*p = x
	return p
}

func (x WorkoutType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkoutType) Descriptor() protoreflect.EnumDescriptor {
	return file_runthread_v1_runthread_proto_enumTypes[5].Descriptor()
}

func (WorkoutType) Type() protoreflect.EnumType {
	return &file_runthread_v1_runthread_proto_enumTypes[5]
}

func (x WorkoutType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkoutType.Descriptor instead.
func (WorkoutType) EnumDescriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{5}
}

type PlannedWorkoutStatus int32

const (
	PlannedWorkoutStatus_PLANNED_WORKOUT_STATUS_UNSPECIFIED PlannedWorkoutStatus = 0
	PlannedWorkoutStatus_PLANNED_WORKOUT_STATUS_SCHEDULED   PlannedWorkoutStatus = 1
	PlannedWorkoutStatus_PLANNED_WORKOUT_STATUS_COMPLETED   PlannedWorkoutStatus = 2
	PlannedWorkoutStatus_PLANNED_WORKOUT_STATUS_MISSED      PlannedWorkoutStatus = 3
	PlannedWorkoutStatus_PLANNED_WORKOUT_STATUS_SKIPPED     PlannedWorkoutStatus = 4
	PlannedWorkoutStatus_PLANNED_WORKOUT_STATUS_MOVED       PlannedWorkoutStatus = 5
)

// Enum value maps for PlannedWorkoutStatus.
var (
	PlannedWorkoutStatus_name = map[int32]string{
		0: "PLANNED_WORKOUT_STATUS_UNSPECIFIED",
		1: "PLANNED_WORKOUT_STATUS_SCHEDULED",
		2: "PLANNED_WORKOUT_STATUS_COMPLETED",
		3: "PLANNED_WORKOUT_STATUS_MISSED",
		4: "PLANNED_WORKOUT_STATUS_SKIPPED",
		5: "PLANNED_WORKOUT_STATUS_MOVED",
	}
	PlannedWorkoutStatus_value = map[string]int32{
		"PLANNED_WORKOUT_STATUS_UNSPECIFIED": 0,
		"PLANNED_WORKOUT_STATUS_SCHEDULED":   1,
		"PLANNED_WORKOUT_STATUS_COMPLETED":   2,
		"PLANNED_WORKOUT_STATUS_MISSED":      3,
		"PLANNED_WORKOUT_STATUS_SKIPPED":     4,
		"PLANNED_WORKOUT_STATUS_MOVED":       5,
	}
)

func (x PlannedWorkoutStatus) Enum() *PlannedWorkoutStatus {
	p := new(PlannedWorkoutStatus)
	*p = x
	return p
}

func (x PlannedWorkoutStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlannedWorkoutStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_runthread_v1_runthread_proto_enumTypes[6].Descriptor()
}

func (PlannedWorkoutStatus) Type() protoreflect.EnumType {
	return &file_runthread_v1_runthread_proto_enumTypes[6]
}

func (x PlannedWorkoutStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlannedWorkoutStatus.Descriptor instead.
func (PlannedWorkoutStatus) EnumDescriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{6}
}

type ActivityType int32

const (
	ActivityType_ACTIVITY_TYPE_UNSPECIFIED ActivityType = 0
	ActivityType_ACTIVITY_TYPE_RUN         ActivityType = 1
	ActivityType_ACTIVITY_TYPE_TRAIL_RUN   ActivityType = 2
	ActivityType_ACTIVITY_TYPE_TREADMILL   ActivityType = 3
	ActivityType_ACTIVITY_TYPE_WALK        ActivityType = 4
	ActivityType_ACTIVITY_TYPE_OTHER       ActivityType = 5
)

// Enum value maps for ActivityType.
var (
	ActivityType_name = map[int32]string{
		0: "ACTIVITY_TYPE_UNSPECIFIED",
		1: "ACTIVITY_TYPE_RUN",
		2: "ACTIVITY_TYPE_TRAIL_RUN",
		3: "ACTIVITY_TYPE_TREADMILL",
		4: "ACTIVITY_TYPE_WALK",
		5: "ACTIVITY_TYPE_OTHER",
	}
	ActivityType_value = map[string]int32{
		"ACTIVITY_TYPE_UNSPECIFIED": 0,
		"ACTIVITY_TYPE_RUN":         1,
		"ACTIVITY_TYPE_TRAIL_RUN":   2,
		"ACTIVITY_TYPE_TREADMILL":   3,
		"ACTIVITY_TYPE_WALK":        4,
		"ACTIVITY_TYPE_OTHER":       5,
	}
)

func (x ActivityType) Enum() *ActivityType {
	p := new(ActivityType)
	*p = x
	return p
}

func (x ActivityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivityType) Descriptor() protoreflect.EnumDescriptor {
	return file_runthread_v1_runthread_proto_enumTypes[7].Descriptor()
}

func (ActivityType) Type() protoreflect.EnumType {
	return &file_runthread_v1_runthread_proto_enumTypes[7]
}

func (x ActivityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActivityType.Descriptor instead.
func (ActivityType) EnumDescriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{7}
}

type WorkoutMatchStatus int32

const (
	WorkoutMatchStatus_WORKOUT_MATCH_STATUS_UNSPECIFIED WorkoutMatchStatus = 0
	WorkoutMatchStatus_WORKOUT_MATCH_STATUS_MATCHED     WorkoutMatchStatus = 1
	WorkoutMatchStatus_WORKOUT_MATCH_STATUS_UNCERTAIN   WorkoutMatchStatus = 2
	WorkoutMatchStatus_WORKOUT_MATCH_STATUS_REJECTED    WorkoutMatchStatus = 3
)

// Enum value maps for WorkoutMatchStatus.
var (
	WorkoutMatchStatus_name = map[int32]string{
		0: "WORKOUT_MATCH_STATUS_UNSPECIFIED",
		1: "WORKOUT_MATCH_STATUS_MATCHED",
		2: "WORKOUT_MATCH_STATUS_UNCERTAIN",
		3: "WORKOUT_MATCH_STATUS_REJECTED",
	}
	WorkoutMatchStatus_value = map[string]int32{
		"WORKOUT_MATCH_STATUS_UNSPECIFIED": 0,
		"WORKOUT_MATCH_STATUS_MATCHED":     1,
		"WORKOUT_MATCH_STATUS_UNCERTAIN":   2,
		"WORKOUT_MATCH_STATUS_REJECTED":    3,
	}
)

func (x WorkoutMatchStatus) Enum() *WorkoutMatchStatus {
	p := new(WorkoutMatchStatus)
	*p = x
	return p
}

func (x WorkoutMatchStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkoutMatchStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_runthread_v1_runthread_proto_enumTypes[8].Descriptor()
}

func (WorkoutMatchStatus) Type() protoreflect.EnumType {
	return &file_runthread_v1_runthread_proto_enumTypes[8]
}

func (x WorkoutMatchStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkoutMatchStatus.Descriptor instead.
func (WorkoutMatchStatus) EnumDescriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{8}
}

type MatchConfidence int32

const (
	MatchConfidence_MATCH_CONFIDENCE_UNSPECIFIED MatchConfidence = 0
	MatchConfidence_MATCH_CONFIDENCE_HIGH        MatchConfidence = 1
	MatchConfidence_MATCH_CONFIDENCE_MEDIUM      MatchConfidence = 2
	MatchConfidence_MATCH_CONFIDENCE_LOW         MatchConfidence = 3
)

// Enum value maps for MatchConfidence.
var (
	MatchConfidence_name = map[int32]string{
		0: "MATCH_CONFIDENCE_UNSPECIFIED",
		1: "MATCH_CONFIDENCE_HIGH",
		2: "MATCH_CONFIDENCE_MEDIUM",
		3: "MATCH_CONFIDENCE_LOW",
	}
	MatchConfidence_value = map[string]int32{
		"MATCH_CONFIDENCE_UNSPECIFIED": 0,
		"MATCH_CONFIDENCE_HIGH":        1,
		"MATCH_CONFIDENCE_MEDIUM":      2,
		"MATCH_CONFIDENCE_LOW":         3,
	}
)

func (x MatchConfidence) Enum() *MatchConfidence {
	p := new(MatchConfidence)
	*p = x
	return p
}

func (x MatchConfidence) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchConfidence) Descriptor() protoreflect.EnumDescriptor {
	return file_runthread_v1_runthread_proto_enumTypes[9].Descriptor()
}

func (MatchConfidence) Type() protoreflect.EnumType {
	return &file_runthread_v1_runthread_proto_enumTypes[9]
}

func (x MatchConfidence) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchConfidence.Descriptor instead.
func (MatchConfidence) EnumDescriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{9}
}

type MatchSource int32

const (
	MatchSource_MATCH_SOURCE_UNSPECIFIED MatchSource = 0
	MatchSource_MATCH_SOURCE_AUTOMATIC   MatchSource = 1
	MatchSource_MATCH_SOURCE_MANUAL      MatchSource = 2
)

// Enum value maps for MatchSource.
var (
	MatchSource_name = map[int32]string{
		0: "MATCH_SOURCE_UNSPECIFIED",
		1: "MATCH_SOURCE_AUTOMATIC",
		2: "MATCH_SOURCE_MANUAL",
	}
	MatchSource_value = map[string]int32{
		"MATCH_SOURCE_UNSPECIFIED": 0,
		"MATCH_SOURCE_AUTOMATIC":   1,
		"MATCH_SOURCE_MANUAL":      2,
	}
)

func (x MatchSource) Enum() *MatchSource {
	p := new(MatchSource)
	*p = x
	return p
}

func (x MatchSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchSource) Descriptor() protoreflect.EnumDescriptor {
	return file_runthread_v1_runthread_proto_enumTypes[10].Descriptor()
}

func (MatchSource) Type() protoreflect.EnumType {
	return &file_runthread_v1_runthread_proto_enumTypes[10]
}

func (x MatchSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchSource.Descriptor instead.
func (MatchSource) EnumDescriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{10}
}

type WorkoutOutcome int32

const (
	WorkoutOutcome_WORKOUT_OUTCOME_UNSPECIFIED          WorkoutOutcome = 0
	WorkoutOutcome_WORKOUT_OUTCOME_COMPLETED_AS_PLANNED WorkoutOutcome = 1
	WorkoutOutcome_WORKOUT_OUTCOME_PARTIALLY_COMPLETED  WorkoutOutcome = 2
	WorkoutOutcome_WORKOUT_OUTCOME_MISSED               WorkoutOutcome = 3
	WorkoutOutcome_WORKOUT_OUTCOME_SKIPPED              WorkoutOutcome = 4
	WorkoutOutcome_WORKOUT_OUTCOME_MOVED                WorkoutOutcome = 5
	WorkoutOutcome_WORKOUT_OUTCOME_OVERPERFORMED        WorkoutOutcome = 6
	WorkoutOutcome_WORKOUT_OUTCOME_UNDERPERFORMED       WorkoutOutcome = 7
)

// Enum value maps for WorkoutOutcome.
var (
	WorkoutOutcome_name = map[int32]string{
		0: "WORKOUT_OUTCOME_UNSPECIFIED",
		1: "WORKOUT_OUTCOME_COMPLETED_AS_PLANNED",
		2: "WORKOUT_OUTCOME_PARTIALLY_COMPLETED",
		3: "WORKOUT_OUTCOME_MISSED",
		4: "WORKOUT_OUTCOME_SKIPPED",
		5: "WORKOUT_OUTCOME_MOVED",
		6: "WORKOUT_OUTCOME_OVERPERFORMED",
		7: "WORKOUT_OUTCOME_UNDERPERFORMED",
	}
	WorkoutOutcome_value = map[string]int32{
		"WORKOUT_OUTCOME_UNSPECIFIED":          0,
		"WORKOUT_OUTCOME_COMPLETED_AS_PLANNED": 1,
		"WORKOUT_OUTCOME_PARTIALLY_COMPLETED":  2,
		"WORKOUT_OUTCOME_MISSED":               3,
		"WORKOUT_OUTCOME_SKIPPED":              4,
		"WORKOUT_OUTCOME_MOVED":                5,
		"WORKOUT_OUTCOME_OVERPERFORMED":        6,
		"WORKOUT_OUTCOME_UNDERPERFORMED":       7,
	}
)

func (x WorkoutOutcome) Enum() *WorkoutOutcome {
	p := new(WorkoutOutcome)
	*p = x
	return p
}

func (x WorkoutOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkoutOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_runthread_v1_runthread_proto_enumTypes[11].Descriptor()
}

func (WorkoutOutcome) Type() protoreflect.EnumType {
	return &file_runthread_v1_runthread_proto_enumTypes[11]
}

func (x WorkoutOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkoutOutcome.Descriptor instead.
func (WorkoutOutcome) EnumDescriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{11}
}

type AdaptationType int32

const (
	AdaptationType_ADAPTATION_TYPE_UNSPECIFIED        AdaptationType = 0
	AdaptationType_ADAPTATION_TYPE_MISSED_WORKOUT     AdaptationType = 1
	AdaptationType_ADAPTATION_TYPE_PARTIAL_COMPLETION AdaptationType = 2
	AdaptationType_ADAPTATION_TYPE_OVERPERFORMANCE    AdaptationType = 3
	AdaptationType_ADAPTATION_TYPE_UNDERPERFORMANCE   AdaptationType = 4
	AdaptationType_ADAPTATION_TYPE_SCHEDULE_CHANGE    AdaptationType = 5
)

// Enum value maps for AdaptationType.
var (
	AdaptationType_name = map[int32]string{
		0: "ADAPTATION_TYPE_UNSPECIFIED",
		1: "ADAPTATION_TYPE_MISSED_WORKOUT",
		2: "ADAPTATION_TYPE_PARTIAL_COMPLETION",
		3: "ADAPTATION_TYPE_OVERPERFORMANCE",
		4: "ADAPTATION_TYPE_UNDERPERFORMANCE",
		5: "ADAPTATION_TYPE_SCHEDULE_CHANGE",
	}
	AdaptationType_value = map[string]int32{
		"ADAPTATION_TYPE_UNSPECIFIED":        0,
		"ADAPTATION_TYPE_MISSED_WORKOUT":     1,
		"ADAPTATION_TYPE_PARTIAL_COMPLETION": 2,
		"ADAPTATION_TYPE_OVERPERFORMANCE":    3,
		"ADAPTATION_TYPE_UNDERPERFORMANCE":   4,
		"ADAPTATION_TYPE_SCHEDULE_CHANGE":    5,
	}
)

func (x AdaptationType) Enum() *AdaptationType {
	p := new(AdaptationType)
	*p = x
	return p
}

func (x AdaptationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdaptationType) Descriptor() protoreflect.EnumDescriptor {
	return file_runthread_v1_runthread_proto_enumTypes[12].Descriptor()
}

func (AdaptationType) Type() protoreflect.EnumType {
	return &file_runthread_v1_runthread_proto_enumTypes[12]
}

func (x AdaptationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdaptationType.Descriptor instead.
func (AdaptationType) EnumDescriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{12}
}

type PlanChangeType int32

const (
	PlanChangeType_PLAN_CHANGE_TYPE_UNSPECIFIED      PlanChangeType = 0
	PlanChangeType_PLAN_CHANGE_TYPE_WORKOUT_MOVED    PlanChangeType = 1
	PlanChangeType_PLAN_CHANGE_TYPE_WORKOUT_REMOVED  PlanChangeType = 2
	PlanChangeType_PLAN_CHANGE_TYPE_WORKOUT_ADDED    PlanChangeType = 3
	PlanChangeType_PLAN_CHANGE_TYPE_WORKOUT_ADJUSTED PlanChangeType = 4
	PlanChangeType_PLAN_CHANGE_TYPE_PLAN_NOTE_ADDED  PlanChangeType = 5
)

// Enum value maps for PlanChangeType.
var (
	PlanChangeType_name = map[int32]string{
		0: "PLAN_CHANGE_TYPE_UNSPECIFIED",
		1: "PLAN_CHANGE_TYPE_WORKOUT_MOVED",
		2: "PLAN_CHANGE_TYPE_WORKOUT_REMOVED",
		3: "PLAN_CHANGE_TYPE_WORKOUT_ADDED",
		4: "PLAN_CHANGE_TYPE_WORKOUT_ADJUSTED",
		5: "PLAN_CHANGE_TYPE_PLAN_NOTE_ADDED",
	}
	PlanChangeType_value = map[string]int32{
		"PLAN_CHANGE_TYPE_UNSPECIFIED":      0,
		"PLAN_CHANGE_TYPE_WORKOUT_MOVED":    1,
		"PLAN_CHANGE_TYPE_WORKOUT_REMOVED":  2,
		"PLAN_CHANGE_TYPE_WORKOUT_ADDED":    3,
		"PLAN_CHANGE_TYPE_WORKOUT_ADJUSTED": 4,
		"PLAN_CHANGE_TYPE_PLAN_NOTE_ADDED":  5,
	}
)

func (x PlanChangeType) Enum() *PlanChangeType {
	p := new(PlanChangeType)
	*p = x
	return p
}

func (x PlanChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlanChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_runthread_v1_runthread_proto_enumTypes[13].Descriptor()
}

func (PlanChangeType) Type() protoreflect.EnumType {
	return &file_runthread_v1_runthread_proto_enumTypes[13]
}

func (x PlanChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlanChangeType.Descriptor instead.
func (PlanChangeType) EnumDescriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{13}
}

type GetCurrentPlanWeekRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AthleteId      string                 `protobuf:"bytes,1,opt,name=athlete_id,json=athleteId,proto3" json:"athlete_id,omitempty"`
	GoalId         string                 `protobuf:"bytes,2,opt,name=goal_id,json=goalId,proto3" json:"goal_id,omitempty"`
	TargetWeekDate string                 `protobuf:"bytes,3,opt,name=target_week_date,json=targetWeekDate,proto3" json:"target_week_date,omitempty"`
	PlanWeekId     string                 `protobuf:"bytes,4,opt,name=plan_week_id,json=planWeekId,proto3" json:"plan_week_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetCurrentPlanWeekRequest) Reset() {
	*x = GetCurrentPlanWeekRequest{}
	mi := &file_runthread_v1_runthread_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentPlanWeekRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentPlanWeekRequest) ProtoMessage() {}

func (x *GetCurrentPlanWeekRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runthread_v1_runthread_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentPlanWeekRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentPlanWeekRequest) Descriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{0}
}

func (x *GetCurrentPlanWeekRequest) GetAthleteId() string {
	if x != nil {
		return x.AthleteId
	}
	return ""
}

func (x *GetCurrentPlanWeekRequest) GetGoalId() string {
	if x != nil {
		return x.GoalId
	}
	return ""
}

func (x *GetCurrentPlanWeekRequest) GetTargetWeekDate() string {
	if x != nil {
		return x.TargetWeekDate
	}
	return ""
}

func (x *GetCurrentPlanWeekRequest) GetPlanWeekId() string {
	if x != nil {
		return x.PlanWeekId
	}
	return ""
}

type GetCurrentPlanWeekResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PlanWeek           *PlanWeek              `protobuf:"bytes,1,opt,name=plan_week,json=planWeek,proto3" json:"plan_week,omitempty"`
	ImportedActivities []*ImportedActivity    `protobuf:"bytes,2,rep,name=imported_activities,json=importedActivities,proto3" json:"imported_activities,omitempty"`
	WorkoutMatches     []*WorkoutMatch        `protobuf:"bytes,3,rep,name=workout_matches,json=workoutMatches,proto3" json:"workout_matches,omitempty"`
	WorkoutResults     []*WorkoutResult       `protobuf:"bytes,4,rep,name=workout_results,json=workoutResults,proto3" json:"workout_results,omitempty"`
	AdaptationEvents   []*AdaptationEvent     `protobuf:"bytes,5,rep,name=adaptation_events,json=adaptationEvents,proto3" json:"adaptation_events,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetCurrentPlanWeekResponse) Reset() {
	*x = GetCurrentPlanWeekResponse{}
	mi := &file_runthread_v1_runthread_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentPlanWeekResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentPlanWeekResponse) ProtoMessage() {}

func (x *GetCurrentPlanWeekResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runthread_v1_runthread_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentPlanWeekResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentPlanWeekResponse) Descriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurrentPlanWeekResponse) GetPlanWeek() *PlanWeek {
	if x != nil {
		return x.PlanWeek
	}
	return nil
}

func (x *GetCurrentPlanWeekResponse) GetImportedActivities() []*ImportedActivity {
	if x != nil {
		return x.ImportedActivities
	}
	return nil
}

func (x *GetCurrentPlanWeekResponse) GetWorkoutMatches() []*WorkoutMatch {
	if x != nil {
		return x.WorkoutMatches
	}
	return nil
}

func (x *GetCurrentPlanWeekResponse) GetWorkoutResults() []*WorkoutResult {
	if x != nil {
		return x.WorkoutResults
	}
	return nil
}

func (x *GetCurrentPlanWeekResponse) GetAdaptationEvents() []*AdaptationEvent {
	if x != nil {
		return x.AdaptationEvents
	}
	return nil
}

type CompleteImportedActivityRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AthleteProfile   *AthleteProfile        `protobuf:"bytes,1,opt,name=athlete_profile,json=athleteProfile,proto3" json:"athlete_profile,omitempty"`
	TrainingGoal     *TrainingGoal          `protobuf:"bytes,2,opt,name=training_goal,json=trainingGoal,proto3" json:"training_goal,omitempty"`
	TargetWeekDate   string                 `protobuf:"bytes,3,opt,name=target_week_date,json=targetWeekDate,proto3" json:"target_week_date,omitempty"`
	ImportedActivity *ImportedActivity      `protobuf:"bytes,4,opt,name=imported_activity,json=importedActivity,proto3" json:"imported_activity,omitempty"`
	ResultId         string                 `protobuf:"bytes,5,opt,name=result_id,json=resultId,proto3" json:"result_id,omitempty"`
	Outcome          WorkoutOutcome         `protobuf:"varint,6,opt,name=outcome,proto3,enum=runthread.v1.WorkoutOutcome" json:"outcome,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CompleteImportedActivityRequest) Reset() {
	*x = CompleteImportedActivityRequest{}
	mi := &file_runthread_v1_runthread_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteImportedActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteImportedActivityRequest) ProtoMessage() {}

func (x *CompleteImportedActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runthread_v1_runthread_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteImportedActivityRequest.ProtoReflect.Descriptor instead.
func (*CompleteImportedActivityRequest) Descriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteImportedActivityRequest) GetAthleteProfile() *AthleteProfile {
	if x != nil {
		return x.AthleteProfile
	}
	return nil
}

func (x *CompleteImportedActivityRequest) GetTrainingGoal() *TrainingGoal {
	if x != nil {
		return x.TrainingGoal
	}
	return nil
}

func (x *CompleteImportedActivityRequest) GetTargetWeekDate() string {
	if x != nil {
		return x.TargetWeekDate
	}
	return ""
}

func (x *CompleteImportedActivityRequest) GetImportedActivity() *ImportedActivity {
	if x != nil {
		return x.ImportedActivity
	}
	return nil
}

func (x *CompleteImportedActivityRequest) GetResultId() string {
	if x != nil {
		return x.ResultId
	}
	return ""
}

func (x *CompleteImportedActivityRequest) GetOutcome() WorkoutOutcome {
	if x != nil {
		return x.Outcome
	}
	return WorkoutOutcome_WORKOUT_OUTCOME_UNSPECIFIED
}

type CompleteImportedActivityResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PlanWeek         *PlanWeek              `protobuf:"bytes,1,opt,name=plan_week,json=planWeek,proto3" json:"plan_week,omitempty"`
	ImportedActivity *ImportedActivity      `protobuf:"bytes,2,opt,name=imported_activity,json=importedActivity,proto3" json:"imported_activity,omitempty"`
	WorkoutMatch     *WorkoutMatch          `protobuf:"bytes,3,opt,name=workout_match,json=workoutMatch,proto3" json:"workout_match,omitempty"`
	UpdatedWorkout   *PlannedWorkout        `protobuf:"bytes,4,opt,name=updated_workout,json=updatedWorkout,proto3" json:"updated_workout,omitempty"`
	WorkoutResult    *WorkoutResult         `protobuf:"bytes,5,opt,name=workout_result,json=workoutResult,proto3" json:"workout_result,omitempty"`
	AdaptationEvent  *AdaptationEvent       `protobuf:"bytes,6,opt,name=adaptation_event,json=adaptationEvent,proto3" json:"adaptation_event,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CompleteImportedActivityResponse) Reset() {
	*x = CompleteImportedActivityResponse{}
	mi := &file_runthread_v1_runthread_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteImportedActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteImportedActivityResponse) ProtoMessage() {}

func (x *CompleteImportedActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runthread_v1_runthread_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteImportedActivityResponse.ProtoReflect.Descriptor instead.
func (*CompleteImportedActivityResponse) Descriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteImportedActivityResponse) GetPlanWeek() *PlanWeek {
	if x != nil {
		return x.PlanWeek
	}
	return nil
}

func (x *CompleteImportedActivityResponse) GetImportedActivity() *ImportedActivity {
	if x != nil {
		return x.ImportedActivity
	}
	return nil
}

func (x *CompleteImportedActivityResponse) GetWorkoutMatch() *WorkoutMatch {
	if x != nil {
		return x.WorkoutMatch
	}
	return nil
}

func (x *CompleteImportedActivityResponse) GetUpdatedWorkout() *PlannedWorkout {
	if x != nil {
		return x.UpdatedWorkout
	}
	return nil
}

func (x *CompleteImportedActivityResponse) GetWorkoutResult() *WorkoutResult {
	if x != nil {
		return x.WorkoutResult
	}
	return nil
}

func (x *CompleteImportedActivityResponse) GetAdaptationEvent() *AdaptationEvent {
	if x != nil {
		return x.AdaptationEvent
	}
	return nil
}

type GetProviderConnectionStatusRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AthleteId            string                 `protobuf:"bytes,1,opt,name=athlete_id,json=athleteId,proto3" json:"athlete_id,omitempty"`
	Provider             Provider               `protobuf:"varint,2,opt,name=provider,proto3,enum=runthread.v1.Provider" json:"provider,omitempty"`
	ProviderConnectionId string                 `protobuf:"bytes,3,opt,name=provider_connection_id,json=providerConnectionId,proto3" json:"provider_connection_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetProviderConnectionStatusRequest) Reset() {
	*x = GetProviderConnectionStatusRequest{}
	mi := &file_runthread_v1_runthread_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderConnectionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderConnectionStatusRequest) ProtoMessage() {}

func (x *GetProviderConnectionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runthread_v1_runthread_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderConnectionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetProviderConnectionStatusRequest) Descriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{4}
}

func (x *GetProviderConnectionStatusRequest) GetAthleteId() string {
	if x != nil {
		return x.AthleteId
	}
	return ""
}

func (x *GetProviderConnectionStatusRequest) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *GetProviderConnectionStatusRequest) GetProviderConnectionId() string {
	if x != nil {
		return x.ProviderConnectionId
	}
	return ""
}

type GetProviderConnectionStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connection    *ProviderConnection    `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	HasConnection bool                   `protobuf:"varint,2,opt,name=has_connection,json=hasConnection,proto3" json:"has_connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderConnectionStatusResponse) Reset() {
	*x = GetProviderConnectionStatusResponse{}
	mi := &file_runthread_v1_runthread_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderConnectionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderConnectionStatusResponse) ProtoMessage() {}

func (x *GetProviderConnectionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runthread_v1_runthread_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderConnectionStatusResponse.ProtoReflect.Descriptor instead.
func (*GetProviderConnectionStatusResponse) Descriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{5}
}

func (x *GetProviderConnectionStatusResponse) GetConnection() *ProviderConnection {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *GetProviderConnectionStatusResponse) GetHasConnection() bool {
	if x != nil {
		return x.HasConnection
	}
	return false
}

type StartProviderConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AthleteId     string                 `protobuf:"bytes,1,opt,name=athlete_id,json=athleteId,proto3" json:"athlete_id,omitempty"`
	Provider      Provider               `protobuf:"varint,2,opt,name=provider,proto3,enum=runthread.v1.Provider" json:"provider,omitempty"`
	RedirectUri   string                 `protobuf:"bytes,3,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProviderConnectionRequest) Reset() {
	*x = StartProviderConnectionRequest{}
	mi := &file_runthread_v1_runthread_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProviderConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProviderConnectionRequest) ProtoMessage() {}

func (x *StartProviderConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runthread_v1_runthread_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProviderConnectionRequest.ProtoReflect.Descriptor instead.
func (*StartProviderConnectionRequest) Descriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{6}
}

func (x *StartProviderConnectionRequest) GetAthleteId() string {
	if x != nil {
		return x.AthleteId
	}
	return ""
}

func (x *StartProviderConnectionRequest) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *StartProviderConnectionRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

type StartProviderConnectionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Connection       *ProviderConnection    `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	AuthorizationUrl string                 `protobuf:"bytes,2,opt,name=authorization_url,json=authorizationUrl,proto3" json:"authorization_url,omitempty"`
	State            string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	OauthReady       bool                   `protobuf:"varint,4,opt,name=oauth_ready,json=oauthReady,proto3" json:"oauth_ready,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StartProviderConnectionResponse) Reset() {
	*x = StartProviderConnectionResponse{}
	mi := &file_runthread_v1_runthread_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProviderConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProviderConnectionResponse) ProtoMessage() {}

func (x *StartProviderConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runthread_v1_runthread_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProviderConnectionResponse.ProtoReflect.Descriptor instead.
func (*StartProviderConnectionResponse) Descriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{7}
}

func (x *StartProviderConnectionResponse) GetConnection() *ProviderConnection {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *StartProviderConnectionResponse) GetAuthorizationUrl() string {
	if x != nil {
		return x.AuthorizationUrl
	}
	return ""
}

func (x *StartProviderConnectionResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *StartProviderConnectionResponse) GetOauthReady() bool {
	if x != nil {
		return x.OauthReady
	}
	return false
}

type ProviderConnection struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	Id             string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AthleteId      string                   `protobuf:"bytes,2,opt,name=athlete_id,json=athleteId,proto3" json:"athlete_id,omitempty"`
	Provider       Provider                 `protobuf:"varint,3,opt,name=provider,proto3,enum=runthread.v1.Provider" json:"provider,omitempty"`
	ProviderUserId string                   `protobuf:"bytes,4,opt,name=provider_user_id,json=providerUserId,proto3" json:"provider_user_id,omitempty"`
	Status         ProviderConnectionStatus `protobuf:"varint,5,opt,name=status,proto3,enum=runthread.v1.ProviderConnectionStatus" json:"status,omitempty"`
	ConnectedAt    *timestamppb.Timestamp   `protobuf:"bytes,6,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	DisconnectedAt *timestamppb.Timestamp   `protobuf:"bytes,7,opt,name=disconnected_at,json=disconnectedAt,proto3" json:"disconnected_at,omitempty"`
	LastSyncAt     *timestamppb.Timestamp   `protobuf:"bytes,8,opt,name=last_sync_at,json=lastSyncAt,proto3" json:"last_sync_at,omitempty"`
	LastError      string                   `protobuf:"bytes,9,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProviderConnection) Reset() {
	*x = ProviderConnection{}
	mi := &file_runthread_v1_runthread_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderConnection) ProtoMessage() {}

func (x *ProviderConnection) ProtoReflect() protoreflect.Message {
	mi := &file_runthread_v1_runthread_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderConnection.ProtoReflect.Descriptor instead.
func (*ProviderConnection) Descriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{8}
}

func (x *ProviderConnection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProviderConnection) GetAthleteId() string {
	if x != nil {
		return x.AthleteId
	}
	return ""
}

func (x *ProviderConnection) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *ProviderConnection) GetProviderUserId() string {
	if x != nil {
		return x.ProviderUserId
	}
	return ""
}

func (x *ProviderConnection) GetStatus() ProviderConnectionStatus {
	if x != nil {
		return x.Status
	}
	return ProviderConnectionStatus_PROVIDER_CONNECTION_STATUS_UNSPECIFIED
}

func (x *ProviderConnection) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

func (x *ProviderConnection) GetDisconnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DisconnectedAt
	}
	return nil
}

func (x *ProviderConnection) GetLastSyncAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSyncAt
	}
	return nil
}

func (x *ProviderConnection) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type AthleteProfile struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	Id                          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName                 string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	ExperienceLevel             ExperienceLevel        `protobuf:"varint,3,opt,name=experience_level,json=experienceLevel,proto3,enum=runthread.v1.ExperienceLevel" json:"experience_level,omitempty"`
	CurrentWeeklyDistanceMeters float64                `protobuf:"fixed64,4,opt,name=current_weekly_distance_meters,json=currentWeeklyDistanceMeters,proto3" json:"current_weekly_distance_meters,omitempty"`
	PreferredRunDays            []int32                `protobuf:"varint,5,rep,packed,name=preferred_run_days,json=preferredRunDays,proto3" json:"preferred_run_days,omitempty"`
	Constraints                 []string               `protobuf:"bytes,6,rep,name=constraints,proto3" json:"constraints,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *AthleteProfile) Reset() {
	*x = AthleteProfile{}
	mi := &file_runthread_v1_runthread_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AthleteProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AthleteProfile) ProtoMessage() {}

func (x *AthleteProfile) ProtoReflect() protoreflect.Message {
	mi := &file_runthread_v1_runthread_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AthleteProfile.ProtoReflect.Descriptor instead.
func (*AthleteProfile) Descriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{9}
}

func (x *AthleteProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AthleteProfile) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AthleteProfile) GetExperienceLevel() ExperienceLevel {
	if x != nil {
		return x.ExperienceLevel
	}
	return ExperienceLevel_EXPERIENCE_LEVEL_UNSPECIFIED
}

func (x *AthleteProfile) GetCurrentWeeklyDistanceMeters() float64 {
	if x != nil {
		return x.CurrentWeeklyDistanceMeters
	}
	return 0
}

func (x *AthleteProfile) GetPreferredRunDays() []int32 {
	if x != nil {
		return x.PreferredRunDays
	}
	return nil
}

func (x *AthleteProfile) GetConstraints() []string {
	if x != nil {
		return x.Constraints
	}
	return nil
}

type TrainingGoal struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AthleteId             string                 `protobuf:"bytes,2,opt,name=athlete_id,json=athleteId,proto3" json:"athlete_id,omitempty"`
	Type                  GoalType               `protobuf:"varint,3,opt,name=type,proto3,enum=runthread.v1.GoalType" json:"type,omitempty"`
	TargetDate            string                 `protobuf:"bytes,4,opt,name=target_date,json=targetDate,proto3" json:"target_date,omitempty"`
	TargetDistanceMeters  float64                `protobuf:"fixed64,5,opt,name=target_distance_meters,json=targetDistanceMeters,proto3" json:"target_distance_meters,omitempty"`
	TargetDurationSeconds int64                  `protobuf:"varint,6,opt,name=target_duration_seconds,json=targetDurationSeconds,proto3" json:"target_duration_seconds,omitempty"`
	Notes                 string                 `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TrainingGoal) Reset() {
	*x = TrainingGoal{}
	mi := &file_runthread_v1_runthread_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingGoal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingGoal) ProtoMessage() {}

func (x *TrainingGoal) ProtoReflect() protoreflect.Message {
	mi := &file_runthread_v1_runthread_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingGoal.ProtoReflect.Descriptor instead.
func (*TrainingGoal) Descriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{10}
}

func (x *TrainingGoal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TrainingGoal) GetAthleteId() string {
	if x != nil {
		return x.AthleteId
	}
	return ""
}

func (x *TrainingGoal) GetType() GoalType {
	if x != nil {
		return x.Type
	}
	return GoalType_GOAL_TYPE_UNSPECIFIED
}

func (x *TrainingGoal) GetTargetDate() string {
	if x != nil {
		return x.TargetDate
	}
	return ""
}

func (x *TrainingGoal) GetTargetDistanceMeters() float64 {
	if x != nil {
		return x.TargetDistanceMeters
	}
	return 0
}

func (x *TrainingGoal) GetTargetDurationSeconds() int64 {
	if x != nil {
		return x.TargetDurationSeconds
	}
	return 0
}

func (x *TrainingGoal) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type PlanWeek struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AthleteId     string                 `protobuf:"bytes,2,opt,name=athlete_id,json=athleteId,proto3" json:"athlete_id,omitempty"`
	GoalId        string                 `protobuf:"bytes,3,opt,name=goal_id,json=goalId,proto3" json:"goal_id,omitempty"`
	PlanId        string                 `protobuf:"bytes,4,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	WeekIndex     int32                  `protobuf:"varint,5,opt,name=week_index,json=weekIndex,proto3" json:"week_index,omitempty"`
	StartsOn      string                 `protobuf:"bytes,6,opt,name=starts_on,json=startsOn,proto3" json:"starts_on,omitempty"`
	Focus         WeekFocus              `protobuf:"varint,7,opt,name=focus,proto3,enum=runthread.v1.WeekFocus" json:"focus,omitempty"`
	Workouts      []*PlannedWorkout      `protobuf:"bytes,8,rep,name=workouts,proto3" json:"workouts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanWeek) Reset() {
	*x = PlanWeek{}
	mi := &file_runthread_v1_runthread_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanWeek) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanWeek) ProtoMessage() {}

func (x *PlanWeek) ProtoReflect() protoreflect.Message {
	mi := &file_runthread_v1_runthread_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanWeek.ProtoReflect.Descriptor instead.
func (*PlanWeek) Descriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{11}
}

func (x *PlanWeek) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlanWeek) GetAthleteId() string {
	if x != nil {
		return x.AthleteId
	}
	return ""
}

func (x *PlanWeek) GetGoalId() string {
	if x != nil {
		return x.GoalId
	}
	return ""
}

func (x *PlanWeek) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *PlanWeek) GetWeekIndex() int32 {
	if x != nil {
		return x.WeekIndex
	}
	return 0
}

func (x *PlanWeek) GetStartsOn() string {
	if x != nil {
		return x.StartsOn
	}
	return ""
}

func (x *PlanWeek) GetFocus() WeekFocus {
	if x != nil {
		return x.Focus
	}
	return WeekFocus_WEEK_FOCUS_UNSPECIFIED
}

func (x *PlanWeek) GetWorkouts() []*PlannedWorkout {
	if x != nil {
		return x.Workouts
	}
	return nil
}

type PlannedWorkout struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PlanId                string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	PlanWeekId            string                 `protobuf:"bytes,3,opt,name=plan_week_id,json=planWeekId,proto3" json:"plan_week_id,omitempty"`
	ScheduledFor          string                 `protobuf:"bytes,4,opt,name=scheduled_for,json=scheduledFor,proto3" json:"scheduled_for,omitempty"`
	Type                  WorkoutType            `protobuf:"varint,5,opt,name=type,proto3,enum=runthread.v1.WorkoutType" json:"type,omitempty"`
	Status                PlannedWorkoutStatus   `protobuf:"varint,6,opt,name=status,proto3,enum=runthread.v1.PlannedWorkoutStatus" json:"status,omitempty"`
	TargetDistanceMeters  float64                `protobuf:"fixed64,7,opt,name=target_distance_meters,json=targetDistanceMeters,proto3" json:"target_distance_meters,omitempty"`
	TargetDurationSeconds int64                  `protobuf:"varint,8,opt,name=target_duration_seconds,json=targetDurationSeconds,proto3" json:"target_duration_seconds,omitempty"`
	Intensity             *IntensityTarget       `protobuf:"bytes,9,opt,name=intensity,proto3" json:"intensity,omitempty"`
	Notes                 string                 `protobuf:"bytes,10,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PlannedWorkout) Reset() {
	*x = PlannedWorkout{}
	mi := &file_runthread_v1_runthread_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlannedWorkout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlannedWorkout) ProtoMessage() {}

func (x *PlannedWorkout) ProtoReflect() protoreflect.Message {
	mi := &file_runthread_v1_runthread_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlannedWorkout.ProtoReflect.Descriptor instead.
func (*PlannedWorkout) Descriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{12}
}

func (x *PlannedWorkout) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlannedWorkout) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *PlannedWorkout) GetPlanWeekId() string {
	if x != nil {
		return x.PlanWeekId
	}
	return ""
}

func (x *PlannedWorkout) GetScheduledFor() string {
	if x != nil {
		return x.ScheduledFor
	}
	return ""
}

func (x *PlannedWorkout) GetType() WorkoutType {
	if x != nil {
		return x.Type
	}
	return WorkoutType_WORKOUT_TYPE_UNSPECIFIED
}

func (x *PlannedWorkout) GetStatus() PlannedWorkoutStatus {
	if x != nil {
		return x.Status
	}
	return PlannedWorkoutStatus_PLANNED_WORKOUT_STATUS_UNSPECIFIED
}

func (x *PlannedWorkout) GetTargetDistanceMeters() float64 {
	if x != nil {
		return x.TargetDistanceMeters
	}
	return 0
}

func (x *PlannedWorkout) GetTargetDurationSeconds() int64 {
	if x != nil {
		return x.TargetDurationSeconds
	}
	return 0
}

func (x *PlannedWorkout) GetIntensity() *IntensityTarget {
	if x != nil {
		return x.Intensity
	}
	return nil
}

func (x *PlannedWorkout) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type IntensityTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntensityTarget) Reset() {
	*x = IntensityTarget{}
	mi := &file_runthread_v1_runthread_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntensityTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntensityTarget) ProtoMessage() {}

func (x *IntensityTarget) ProtoReflect() protoreflect.Message {
	mi := &file_runthread_v1_runthread_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntensityTarget.ProtoReflect.Descriptor instead.
func (*IntensityTarget) Descriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{13}
}

func (x *IntensityTarget) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *IntensityTarget) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ImportedActivity struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	Id                             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AthleteId                      string                 `protobuf:"bytes,2,opt,name=athlete_id,json=athleteId,proto3" json:"athlete_id,omitempty"`
	Type                           ActivityType           `protobuf:"varint,3,opt,name=type,proto3,enum=runthread.v1.ActivityType" json:"type,omitempty"`
	StartedAt                      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	DurationSeconds                int64                  `protobuf:"varint,5,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	DistanceMeters                 float64                `protobuf:"fixed64,6,opt,name=distance_meters,json=distanceMeters,proto3" json:"distance_meters,omitempty"`
	AveragePaceSecondsPerKilometer int64                  `protobuf:"varint,7,opt,name=average_pace_seconds_per_kilometer,json=averagePaceSecondsPerKilometer,proto3" json:"average_pace_seconds_per_kilometer,omitempty"`
	AverageHeartBpm                int32                  `protobuf:"varint,8,opt,name=average_heart_bpm,json=averageHeartBpm,proto3" json:"average_heart_bpm,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *ImportedActivity) Reset() {
	*x = ImportedActivity{}
	mi := &file_runthread_v1_runthread_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportedActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportedActivity) ProtoMessage() {}

func (x *ImportedActivity) ProtoReflect() protoreflect.Message {
	mi := &file_runthread_v1_runthread_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportedActivity.ProtoReflect.Descriptor instead.
func (*ImportedActivity) Descriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{14}
}

func (x *ImportedActivity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImportedActivity) GetAthleteId() string {
	if x != nil {
		return x.AthleteId
	}
	return ""
}

func (x *ImportedActivity) GetType() ActivityType {
	if x != nil {
		return x.Type
	}
	return ActivityType_ACTIVITY_TYPE_UNSPECIFIED
}

func (x *ImportedActivity) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ImportedActivity) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *ImportedActivity) GetDistanceMeters() float64 {
	if x != nil {
		return x.DistanceMeters
	}
	return 0
}

func (x *ImportedActivity) GetAveragePaceSecondsPerKilometer() int64 {
	if x != nil {
		return x.AveragePaceSecondsPerKilometer
	}
	return 0
}

func (x *ImportedActivity) GetAverageHeartBpm() int32 {
	if x != nil {
		return x.AverageHeartBpm
	}
	return 0
}

type WorkoutMatch struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PlannedWorkoutId   string                 `protobuf:"bytes,2,opt,name=planned_workout_id,json=plannedWorkoutId,proto3" json:"planned_workout_id,omitempty"`
	ImportedActivityId string                 `protobuf:"bytes,3,opt,name=imported_activity_id,json=importedActivityId,proto3" json:"imported_activity_id,omitempty"`
	Status             WorkoutMatchStatus     `protobuf:"varint,4,opt,name=status,proto3,enum=runthread.v1.WorkoutMatchStatus" json:"status,omitempty"`
	Confidence         MatchConfidence        `protobuf:"varint,5,opt,name=confidence,proto3,enum=runthread.v1.MatchConfidence" json:"confidence,omitempty"`
	MatchedBy          MatchSource            `protobuf:"varint,6,opt,name=matched_by,json=matchedBy,proto3,enum=runthread.v1.MatchSource" json:"matched_by,omitempty"`
	MatchedAt          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=matched_at,json=matchedAt,proto3" json:"matched_at,omitempty"`
	Notes              string                 `protobuf:"bytes,8,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WorkoutMatch) Reset() {
	*x = WorkoutMatch{}
	mi := &file_runthread_v1_runthread_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkoutMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkoutMatch) ProtoMessage() {}

func (x *WorkoutMatch) ProtoReflect() protoreflect.Message {
	mi := &file_runthread_v1_runthread_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkoutMatch.ProtoReflect.Descriptor instead.
func (*WorkoutMatch) Descriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{15}
}

func (x *WorkoutMatch) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkoutMatch) GetPlannedWorkoutId() string {
	if x != nil {
		return x.PlannedWorkoutId
	}
	return ""
}

func (x *WorkoutMatch) GetImportedActivityId() string {
	if x != nil {
		return x.ImportedActivityId
	}
	return ""
}

func (x *WorkoutMatch) GetStatus() WorkoutMatchStatus {
	if x != nil {
		return x.Status
	}
	return WorkoutMatchStatus_WORKOUT_MATCH_STATUS_UNSPECIFIED
}

func (x *WorkoutMatch) GetConfidence() MatchConfidence {
	if x != nil {
		return x.Confidence
	}
	return MatchConfidence_MATCH_CONFIDENCE_UNSPECIFIED
}

func (x *WorkoutMatch) GetMatchedBy() MatchSource {
	if x != nil {
		return x.MatchedBy
	}
	return MatchSource_MATCH_SOURCE_UNSPECIFIED
}

func (x *WorkoutMatch) GetMatchedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MatchedAt
	}
	return nil
}

func (x *WorkoutMatch) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type WorkoutResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PlannedWorkoutId   string                 `protobuf:"bytes,2,opt,name=planned_workout_id,json=plannedWorkoutId,proto3" json:"planned_workout_id,omitempty"`
	ImportedActivityId string                 `protobuf:"bytes,3,opt,name=imported_activity_id,json=importedActivityId,proto3" json:"imported_activity_id,omitempty"`
	Outcome            WorkoutOutcome         `protobuf:"varint,4,opt,name=outcome,proto3,enum=runthread.v1.WorkoutOutcome" json:"outcome,omitempty"`
	CompletedAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	DistanceMeters     float64                `protobuf:"fixed64,6,opt,name=distance_meters,json=distanceMeters,proto3" json:"distance_meters,omitempty"`
	DurationSeconds    int64                  `protobuf:"varint,7,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Notes              string                 `protobuf:"bytes,8,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WorkoutResult) Reset() {
	*x = WorkoutResult{}
	mi := &file_runthread_v1_runthread_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkoutResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkoutResult) ProtoMessage() {}

func (x *WorkoutResult) ProtoReflect() protoreflect.Message {
	mi := &file_runthread_v1_runthread_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkoutResult.ProtoReflect.Descriptor instead.
func (*WorkoutResult) Descriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{16}
}

func (x *WorkoutResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkoutResult) GetPlannedWorkoutId() string {
	if x != nil {
		return x.PlannedWorkoutId
	}
	return ""
}

func (x *WorkoutResult) GetImportedActivityId() string {
	if x != nil {
		return x.ImportedActivityId
	}
	return ""
}

func (x *WorkoutResult) GetOutcome() WorkoutOutcome {
	if x != nil {
		return x.Outcome
	}
	return WorkoutOutcome_WORKOUT_OUTCOME_UNSPECIFIED
}

func (x *WorkoutResult) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *WorkoutResult) GetDistanceMeters() float64 {
	if x != nil {
		return x.DistanceMeters
	}
	return 0
}

func (x *WorkoutResult) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *WorkoutResult) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type AdaptationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PlanId        string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	AthleteId     string                 `protobuf:"bytes,3,opt,name=athlete_id,json=athleteId,proto3" json:"athlete_id,omitempty"`
	Type          AdaptationType         `protobuf:"varint,4,opt,name=type,proto3,enum=runthread.v1.AdaptationType" json:"type,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	Summary       string                 `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Changes       []*PlanChange          `protobuf:"bytes,8,rep,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdaptationEvent) Reset() {
	*x = AdaptationEvent{}
	mi := &file_runthread_v1_runthread_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdaptationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdaptationEvent) ProtoMessage() {}

func (x *AdaptationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_runthread_v1_runthread_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdaptationEvent.ProtoReflect.Descriptor instead.
func (*AdaptationEvent) Descriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{17}
}

func (x *AdaptationEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdaptationEvent) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *AdaptationEvent) GetAthleteId() string {
	if x != nil {
		return x.AthleteId
	}
	return ""
}

func (x *AdaptationEvent) GetType() AdaptationType {
	if x != nil {
		return x.Type
	}
	return AdaptationType_ADAPTATION_TYPE_UNSPECIFIED
}

func (x *AdaptationEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AdaptationEvent) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *AdaptationEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AdaptationEvent) GetChanges() []*PlanChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

type PlanChange struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PlannedWorkoutId string                 `protobuf:"bytes,1,opt,name=planned_workout_id,json=plannedWorkoutId,proto3" json:"planned_workout_id,omitempty"`
	Type             PlanChangeType         `protobuf:"varint,2,opt,name=type,proto3,enum=runthread.v1.PlanChangeType" json:"type,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PlanChange) Reset() {
	*x = PlanChange{}
	mi := &file_runthread_v1_runthread_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanChange) ProtoMessage() {}

func (x *PlanChange) ProtoReflect() protoreflect.Message {
	mi := &file_runthread_v1_runthread_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanChange.ProtoReflect.Descriptor instead.
func (*PlanChange) Descriptor() ([]byte, []int) {
	return file_runthread_v1_runthread_proto_rawDescGZIP(), []int{18}
}

func (x *PlanChange) GetPlannedWorkoutId() string {
	if x != nil {
		return x.PlannedWorkoutId
	}
	return ""
}

func (x *PlanChange) GetType() PlanChangeType {
	if x != nil {
		return x.Type
	}
	return PlanChangeType_PLAN_CHANGE_TYPE_UNSPECIFIED
}

func (x *PlanChange) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_runthread_v1_runthread_proto protoreflect.FileDescriptor

const file_runthread_v1_runthread_proto_rawDesc = "" +
	"\n" +
	"\x1crunthread/v1/runthread.proto\x12\frunthread.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9f\x01\n" +
	"\x19GetCurrentPlanWeekRequest\x12\x1d\n" +
	"\n" +
	"athlete_id\x18\x01 \x01(\tR\tathleteId\x12\x17\n" +
	"\agoal_id\x18\x02 \x01(\tR\x06goalId\x12(\n" +
	"\x10target_week_date\x18\x03 \x01(\tR\x0etargetWeekDate\x12 \n" +
	"\fplan_week_id\x18\x04 \x01(\tR\n" +
	"planWeekId\"\xf9\x02\n" +
	"\x1aGetCurrentPlanWeekResponse\x123\n" +
	"\tplan_week\x18\x01 \x01(\v2\x16.runthread.v1.PlanWeekR\bplanWeek\x12O\n" +
	"\x13imported_activities\x18\x02 \x03(\v2\x1e.runthread.v1.ImportedActivityR\x12importedActivities\x12C\n" +
	"\x0fworkout_matches\x18\x03 \x03(\v2\x1a.runthread.v1.WorkoutMatchR\x0eworkoutMatches\x12D\n" +
	"\x0fworkout_results\x18\x04 \x03(\v2\x1b.runthread.v1.WorkoutResultR\x0eworkoutResults\x12J\n" +
	"\x11adaptation_events\x18\x05 \x03(\v2\x1d.runthread.v1.AdaptationEventR\x10adaptationEvents\"\xf5\x02\n" +
	"\x1fCompleteImportedActivityRequest\x12E\n" +
	"\x0fathlete_profile\x18\x01 \x01(\v2\x1c.runthread.v1.AthleteProfileR\x0eathleteProfile\x12?\n" +
	"\rtraining_goal\x18\x02 \x01(\v2\x1a.runthread.v1.TrainingGoalR\ftrainingGoal\x12(\n" +
	"\x10target_week_date\x18\x03 \x01(\tR\x0etargetWeekDate\x12K\n" +
	"\x11imported_activity\x18\x04 \x01(\v2\x1e.runthread.v1.ImportedActivityR\x10importedActivity\x12\x1b\n" +
	"\tresult_id\x18\x05 \x01(\tR\bresultId\x126\n" +
	"\aoutcome\x18\x06 \x01(\x0e2\x1c.runthread.v1.WorkoutOutcomeR\aoutcome\"\xba\x03\n" +
	" CompleteImportedActivityResponse\x123\n" +
	"\tplan_week\x18\x01 \x01(\v2\x16.runthread.v1.PlanWeekR\bplanWeek\x12K\n" +
	"\x11imported_activity\x18\x02 \x01(\v2\x1e.runthread.v1.ImportedActivityR\x10importedActivity\x12?\n" +
	"\rworkout_match\x18\x03 \x01(\v2\x1a.runthread.v1.WorkoutMatchR\fworkoutMatch\x12E\n" +
	"\x0fupdated_workout\x18\x04 \x01(\v2\x1c.runthread.v1.PlannedWorkoutR\x0eupdatedWorkout\x12B\n" +
	"\x0eworkout_result\x18\x05 \x01(\v2\x1b.runthread.v1.WorkoutResultR\rworkoutResult\x12H\n" +
	"\x10adaptation_event\x18\x06 \x01(\v2\x1d.runthread.v1.AdaptationEventR\x0fadaptationEvent\"\xad\x01\n" +
	"\"GetProviderConnectionStatusRequest\x12\x1d\n" +
	"\n" +
	"athlete_id\x18\x01 \x01(\tR\tathleteId\x122\n" +
	"\bprovider\x18\x02 \x01(\x0e2\x16.runthread.v1.ProviderR\bprovider\x124\n" +
	"\x16provider_connection_id\x18\x03 \x01(\tR\x14providerConnectionId\"\x8e\x01\n" +
	"#GetProviderConnectionStatusResponse\x12@\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2 .runthread.v1.ProviderConnectionR\n" +
	"connection\x12%\n" +
	"\x0ehas_connection\x18\x02 \x01(\bR\rhasConnection\"\x96\x01\n" +
	"\x1eStartProviderConnectionRequest\x12\x1d\n" +
	"\n" +
	"athlete_id\x18\x01 \x01(\tR\tathleteId\x122\n" +
	"\bprovider\x18\x02 \x01(\x0e2\x16.runthread.v1.ProviderR\bprovider\x12!\n" +
	"\fredirect_uri\x18\x03 \x01(\tR\vredirectUri\"\xc7\x01\n" +
	"\x1fStartProviderConnectionResponse\x12@\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2 .runthread.v1.ProviderConnectionR\n" +
	"connection\x12+\n" +
	"\x11authorization_url\x18\x02 \x01(\tR\x10authorizationUrl\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1f\n" +
	"\voauth_ready\x18\x04 \x01(\bR\n" +
	"oauthReady\"\xc2\x03\n" +
	"\x12ProviderConnection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"athlete_id\x18\x02 \x01(\tR\tathleteId\x122\n" +
	"\bprovider\x18\x03 \x01(\x0e2\x16.runthread.v1.ProviderR\bprovider\x12(\n" +
	"\x10provider_user_id\x18\x04 \x01(\tR\x0eproviderUserId\x12>\n" +
	"\x06status\x18\x05 \x01(\x0e2&.runthread.v1.ProviderConnectionStatusR\x06status\x12=\n" +
	"\fconnected_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vconnectedAt\x12C\n" +
	"\x0fdisconnected_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0edisconnectedAt\x12<\n" +
	"\flast_sync_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSyncAt\x12\x1d\n" +
	"\n" +
	"last_error\x18\t \x01(\tR\tlastError\"\xa2\x02\n" +
	"\x0eAthleteProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12H\n" +
	"\x10experience_level\x18\x03 \x01(\x0e2\x1d.runthread.v1.ExperienceLevelR\x0fexperienceLevel\x12C\n" +
	"\x1ecurrent_weekly_distance_meters\x18\x04 \x01(\x01R\x1bcurrentWeeklyDistanceMeters\x12,\n" +
	"\x12preferred_run_days\x18\x05 \x03(\x05R\x10preferredRunDays\x12 \n" +
	"\vconstraints\x18\x06 \x03(\tR\vconstraints\"\x8e\x02\n" +
	"\fTrainingGoal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"athlete_id\x18\x02 \x01(\tR\tathleteId\x12*\n" +
	"\x04type\x18\x03 \x01(\x0e2\x16.runthread.v1.GoalTypeR\x04type\x12\x1f\n" +
	"\vtarget_date\x18\x04 \x01(\tR\n" +
	"targetDate\x124\n" +
	"\x16target_distance_meters\x18\x05 \x01(\x01R\x14targetDistanceMeters\x126\n" +
	"\x17target_duration_seconds\x18\x06 \x01(\x03R\x15targetDurationSeconds\x12\x14\n" +
	"\x05notes\x18\a \x01(\tR\x05notes\"\x90\x02\n" +
	"\bPlanWeek\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"athlete_id\x18\x02 \x01(\tR\tathleteId\x12\x17\n" +
	"\agoal_id\x18\x03 \x01(\tR\x06goalId\x12\x17\n" +
	"\aplan_id\x18\x04 \x01(\tR\x06planId\x12\x1d\n" +
	"\n" +
	"week_index\x18\x05 \x01(\x05R\tweekIndex\x12\x1b\n" +
	"\tstarts_on\x18\x06 \x01(\tR\bstartsOn\x12-\n" +
	"\x05focus\x18\a \x01(\x0e2\x17.runthread.v1.WeekFocusR\x05focus\x128\n" +
	"\bworkouts\x18\b \x03(\v2\x1c.runthread.v1.PlannedWorkoutR\bworkouts\"\xac\x03\n" +
	"\x0ePlannedWorkout\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12 \n" +
	"\fplan_week_id\x18\x03 \x01(\tR\n" +
	"planWeekId\x12#\n" +
	"\rscheduled_for\x18\x04 \x01(\tR\fscheduledFor\x12-\n" +
	"\x04type\x18\x05 \x01(\x0e2\x19.runthread.v1.WorkoutTypeR\x04type\x12:\n" +
	"\x06status\x18\x06 \x01(\x0e2\".runthread.v1.PlannedWorkoutStatusR\x06status\x124\n" +
	"\x16target_distance_meters\x18\a \x01(\x01R\x14targetDistanceMeters\x126\n" +
	"\x17target_duration_seconds\x18\b \x01(\x03R\x15targetDurationSeconds\x12;\n" +
	"\tintensity\x18\t \x01(\v2\x1d.runthread.v1.IntensityTargetR\tintensity\x12\x14\n" +
	"\x05notes\x18\n" +
	" \x01(\tR\x05notes\"G\n" +
	"\x0fIntensityTarget\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\xf8\x02\n" +
	"\x10ImportedActivity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"athlete_id\x18\x02 \x01(\tR\tathleteId\x12.\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1a.runthread.v1.ActivityTypeR\x04type\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12)\n" +
	"\x10duration_seconds\x18\x05 \x01(\x03R\x0fdurationSeconds\x12'\n" +
	"\x0fdistance_meters\x18\x06 \x01(\x01R\x0edistanceMeters\x12J\n" +
	"\"average_pace_seconds_per_kilometer\x18\a \x01(\x03R\x1eaveragePaceSecondsPerKilometer\x12*\n" +
	"\x11average_heart_bpm\x18\b \x01(\x05R\x0faverageHeartBpm\"\x82\x03\n" +
	"\fWorkoutMatch\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x12planned_workout_id\x18\x02 \x01(\tR\x10plannedWorkoutId\x120\n" +
	"\x14imported_activity_id\x18\x03 \x01(\tR\x12importedActivityId\x128\n" +
	"\x06status\x18\x04 \x01(\x0e2 .runthread.v1.WorkoutMatchStatusR\x06status\x12=\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x0e2\x1d.runthread.v1.MatchConfidenceR\n" +
	"confidence\x128\n" +
	"\n" +
	"matched_by\x18\x06 \x01(\x0e2\x19.runthread.v1.MatchSourceR\tmatchedBy\x129\n" +
	"\n" +
	"matched_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tmatchedAt\x12\x14\n" +
	"\x05notes\x18\b \x01(\tR\x05notes\"\xe0\x02\n" +
	"\rWorkoutResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x12planned_workout_id\x18\x02 \x01(\tR\x10plannedWorkoutId\x120\n" +
	"\x14imported_activity_id\x18\x03 \x01(\tR\x12importedActivityId\x126\n" +
	"\aoutcome\x18\x04 \x01(\x0e2\x1c.runthread.v1.WorkoutOutcomeR\aoutcome\x12=\n" +
	"\fcompleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12'\n" +
	"\x0fdistance_meters\x18\x06 \x01(\x01R\x0edistanceMeters\x12)\n" +
	"\x10duration_seconds\x18\a \x01(\x03R\x0fdurationSeconds\x12\x14\n" +
	"\x05notes\x18\b \x01(\tR\x05notes\"\xac\x02\n" +
	"\x0fAdaptationEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12\x1d\n" +
	"\n" +
	"athlete_id\x18\x03 \x01(\tR\tathleteId\x120\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1c.runthread.v1.AdaptationTypeR\x04type\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x18\n" +
	"\asummary\x18\x06 \x01(\tR\asummary\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x122\n" +
	"\achanges\x18\b \x03(\v2\x18.runthread.v1.PlanChangeR\achanges\"\x8e\x01\n" +
	"\n" +
	"PlanChange\x12,\n" +
	"\x12planned_workout_id\x18\x01 \x01(\tR\x10plannedWorkoutId\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.runthread.v1.PlanChangeTypeR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription*\x94\x01\n" +
	"\x0fExperienceLevel\x12 \n" +
	"\x1cEXPERIENCE_LEVEL_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19EXPERIENCE_LEVEL_BEGINNER\x10\x01\x12!\n" +
	"\x1dEXPERIENCE_LEVEL_INTERMEDIATE\x10\x02\x12\x1d\n" +
	"\x19EXPERIENCE_LEVEL_ADVANCED\x10\x03*N\n" +
	"\bProvider\x12\x18\n" +
	"\x14PROVIDER_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPROVIDER_GARMIN\x10\x01\x12\x13\n" +
	"\x0fPROVIDER_STRAVA\x10\x02*\x93\x02\n" +
	"\x18ProviderConnectionStatus\x12*\n" +
	"&PROVIDER_CONNECTION_STATUS_UNSPECIFIED\x10\x00\x12&\n" +
	"\"PROVIDER_CONNECTION_STATUS_PENDING\x10\x01\x12(\n" +
	"$PROVIDER_CONNECTION_STATUS_CONNECTED\x10\x02\x12&\n" +
	"\"PROVIDER_CONNECTION_STATUS_SYNCING\x10\x03\x12$\n" +
	" PROVIDER_CONNECTION_STATUS_ERROR\x10\x04\x12+\n" +
	"'PROVIDER_CONNECTION_STATUS_DISCONNECTED\x10\x05*\x84\x01\n" +
	"\bGoalType\x12\x19\n" +
	"\x15GOAL_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19GOAL_TYPE_GENERAL_FITNESS\x10\x01\x12\x12\n" +
	"\x0eGOAL_TYPE_RACE\x10\x02\x12\x16\n" +
	"\x12GOAL_TYPE_DISTANCE\x10\x03\x12\x12\n" +
	"\x0eGOAL_TYPE_TIME\x10\x04*\x96\x01\n" +
	"\tWeekFocus\x12\x1a\n" +
	"\x16WEEK_FOCUS_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fWEEK_FOCUS_BASE\x10\x01\x12\x14\n" +
	"\x10WEEK_FOCUS_BUILD\x10\x02\x12\x17\n" +
	"\x13WEEK_FOCUS_RECOVERY\x10\x03\x12\x13\n" +
	"\x0fWEEK_FOCUS_PEAK\x10\x04\x12\x14\n" +
	"\x10WEEK_FOCUS_TAPER\x10\x05*\xdb\x01\n" +
	"\vWorkoutType\x12\x1c\n" +
	"\x18WORKOUT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11WORKOUT_TYPE_EASY\x10\x01\x12\x19\n" +
	"\x15WORKOUT_TYPE_LONG_RUN\x10\x02\x12\x18\n" +
	"\x14WORKOUT_TYPE_WORKOUT\x10\x03\x12\x19\n" +
	"\x15WORKOUT_TYPE_RECOVERY\x10\x04\x12\x15\n" +
	"\x11WORKOUT_TYPE_RACE\x10\x05\x12\x15\n" +
	"\x11WORKOUT_TYPE_REST\x10\x06\x12\x19\n" +
	"\x15WORKOUT_TYPE_STRENGTH\x10\a*\xf3\x01\n" +
	"\x14PlannedWorkoutStatus\x12&\n" +
	"\"PLANNED_WORKOUT_STATUS_UNSPECIFIED\x10\x00\x12$\n" +
	" PLANNED_WORKOUT_STATUS_SCHEDULED\x10\x01\x12$\n" +
	" PLANNED_WORKOUT_STATUS_COMPLETED\x10\x02\x12!\n" +
	"\x1dPLANNED_WORKOUT_STATUS_MISSED\x10\x03\x12\"\n" +
	"\x1ePLANNED_WORKOUT_STATUS_SKIPPED\x10\x04\x12 \n" +
	"\x1cPLANNED_WORKOUT_STATUS_MOVED\x10\x05*\xaf\x01\n" +
	"\fActivityType\x12\x1d\n" +
	"\x19ACTIVITY_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ACTIVITY_TYPE_RUN\x10\x01\x12\x1b\n" +
	"\x17ACTIVITY_TYPE_TRAIL_RUN\x10\x02\x12\x1b\n" +
	"\x17ACTIVITY_TYPE_TREADMILL\x10\x03\x12\x16\n" +
	"\x12ACTIVITY_TYPE_WALK\x10\x04\x12\x17\n" +
	"\x13ACTIVITY_TYPE_OTHER\x10\x05*\xa3\x01\n" +
	"\x12WorkoutMatchStatus\x12$\n" +
	" WORKOUT_MATCH_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cWORKOUT_MATCH_STATUS_MATCHED\x10\x01\x12\"\n" +
	"\x1eWORKOUT_MATCH_STATUS_UNCERTAIN\x10\x02\x12!\n" +
	"\x1dWORKOUT_MATCH_STATUS_REJECTED\x10\x03*\x85\x01\n" +
	"\x0fMatchConfidence\x12 \n" +
	"\x1cMATCH_CONFIDENCE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15MATCH_CONFIDENCE_HIGH\x10\x01\x12\x1b\n" +
	"\x17MATCH_CONFIDENCE_MEDIUM\x10\x02\x12\x18\n" +
	"\x14MATCH_CONFIDENCE_LOW\x10\x03*`\n" +
	"\vMatchSource\x12\x1c\n" +
	"\x18MATCH_SOURCE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16MATCH_SOURCE_AUTOMATIC\x10\x01\x12\x17\n" +
	"\x13MATCH_SOURCE_MANUAL\x10\x02*\x9f\x02\n" +
	"\x0eWorkoutOutcome\x12\x1f\n" +
	"\x1bWORKOUT_OUTCOME_UNSPECIFIED\x10\x00\x12(\n" +
	"$WORKOUT_OUTCOME_COMPLETED_AS_PLANNED\x10\x01\x12'\n" +
	"#WORKOUT_OUTCOME_PARTIALLY_COMPLETED\x10\x02\x12\x1a\n" +
	"\x16WORKOUT_OUTCOME_MISSED\x10\x03\x12\x1b\n" +
	"\x17WORKOUT_OUTCOME_SKIPPED\x10\x04\x12\x19\n" +
	"\x15WORKOUT_OUTCOME_MOVED\x10\x05\x12!\n" +
	"\x1dWORKOUT_OUTCOME_OVERPERFORMED\x10\x06\x12\"\n" +
	"\x1eWORKOUT_OUTCOME_UNDERPERFORMED\x10\a*\xed\x01\n" +
	"\x0eAdaptationType\x12\x1f\n" +
	"\x1bADAPTATION_TYPE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eADAPTATION_TYPE_MISSED_WORKOUT\x10\x01\x12&\n" +
	"\"ADAPTATION_TYPE_PARTIAL_COMPLETION\x10\x02\x12#\n" +
	"\x1fADAPTATION_TYPE_OVERPERFORMANCE\x10\x03\x12$\n" +
	" ADAPTATION_TYPE_UNDERPERFORMANCE\x10\x04\x12#\n" +
	"\x1fADAPTATION_TYPE_SCHEDULE_CHANGE\x10\x05*\xed\x01\n" +
	"\x0ePlanChangeType\x12 \n" +
	"\x1cPLAN_CHANGE_TYPE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1ePLAN_CHANGE_TYPE_WORKOUT_MOVED\x10\x01\x12$\n" +
	" PLAN_CHANGE_TYPE_WORKOUT_REMOVED\x10\x02\x12\"\n" +
	"\x1ePLAN_CHANGE_TYPE_WORKOUT_ADDED\x10\x03\x12%\n" +
	"!PLAN_CHANGE_TYPE_WORKOUT_ADJUSTED\x10\x04\x12$\n" +
	" PLAN_CHANGE_TYPE_PLAN_NOTE_ADDED\x10\x052\xf3\x03\n" +
	"\x10RunthreadService\x12g\n" +
	"\x12GetCurrentPlanWeek\x12'.runthread.v1.GetCurrentPlanWeekRequest\x1a(.runthread.v1.GetCurrentPlanWeekResponse\x12\x82\x01\n" +
	"\x1bGetProviderConnectionStatus\x120.runthread.v1.GetProviderConnectionStatusRequest\x1a1.runthread.v1.GetProviderConnectionStatusResponse\x12v\n" +
	"\x17StartProviderConnection\x12,.runthread.v1.StartProviderConnectionRequest\x1a-.runthread.v1.StartProviderConnectionResponse\x12y\n" +
	"\x18CompleteImportedActivity\x12-.runthread.v1.CompleteImportedActivityRequest\x1a..runthread.v1.CompleteImportedActivityResponseBSZQgithub.com/runthread/runthread/services/api/internal/rpc/runthread/v1;runthreadv1b\x06proto3"

var (
	file_runthread_v1_runthread_proto_rawDescOnce sync.Once
	file_runthread_v1_runthread_proto_rawDescData []byte
)

func file_runthread_v1_runthread_proto_rawDescGZIP() []byte {
	file_runthread_v1_runthread_proto_rawDescOnce.Do(func() {
		file_runthread_v1_runthread_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runthread_v1_runthread_proto_rawDesc), len(file_runthread_v1_runthread_proto_rawDesc)))
	})
	return file_runthread_v1_runthread_proto_rawDescData
}

var file_runthread_v1_runthread_proto_enumTypes = make([]protoimpl.EnumInfo, 14)
var file_runthread_v1_runthread_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_runthread_v1_runthread_proto_goTypes = []any{
	(ExperienceLevel)(0),                        // 0: runthread.v1.ExperienceLevel
	(Provider)(0),                               // 1: runthread.v1.Provider
	(ProviderConnectionStatus)(0),               // 2: runthread.v1.ProviderConnectionStatus
	(GoalType)(0),                               // 3: runthread.v1.GoalType
	(WeekFocus)(0),                              // 4: runthread.v1.WeekFocus
	(WorkoutType)(0),                            // 5: runthread.v1.WorkoutType
	(PlannedWorkoutStatus)(0),                   // 6: runthread.v1.PlannedWorkoutStatus
	(ActivityType)(0),                           // 7: runthread.v1.ActivityType
	(WorkoutMatchStatus)(0),                     // 8: runthread.v1.WorkoutMatchStatus
	(MatchConfidence)(0),                        // 9: runthread.v1.MatchConfidence
	(MatchSource)(0),                            // 10: runthread.v1.MatchSource
	(WorkoutOutcome)(0),                         // 11: runthread.v1.WorkoutOutcome
	(AdaptationType)(0),                         // 12: runthread.v1.AdaptationType
	(PlanChangeType)(0),                         // 13: runthread.v1.PlanChangeType
	(*GetCurrentPlanWeekRequest)(nil),           // 14: runthread.v1.GetCurrentPlanWeekRequest
	(*GetCurrentPlanWeekResponse)(nil),          // 15: runthread.v1.GetCurrentPlanWeekResponse
	(*CompleteImportedActivityRequest)(nil),     // 16: runthread.v1.CompleteImportedActivityRequest
	(*CompleteImportedActivityResponse)(nil),    // 17: runthread.v1.CompleteImportedActivityResponse
	(*GetProviderConnectionStatusRequest)(nil),  // 18: runthread.v1.GetProviderConnectionStatusRequest
	(*GetProviderConnectionStatusResponse)(nil), // 19: runthread.v1.GetProviderConnectionStatusResponse
	(*StartProviderConnectionRequest)(nil),      // 20: runthread.v1.StartProviderConnectionRequest
	(*StartProviderConnectionResponse)(nil),     // 21: runthread.v1.StartProviderConnectionResponse
	(*ProviderConnection)(nil),                  // 22: runthread.v1.ProviderConnection
	(*AthleteProfile)(nil),                      // 23: runthread.v1.AthleteProfile
	(*TrainingGoal)(nil),                        // 24: runthread.v1.TrainingGoal
	(*PlanWeek)(nil),                            // 25: runthread.v1.PlanWeek
	(*PlannedWorkout)(nil),                      // 26: runthread.v1.PlannedWorkout
	(*IntensityTarget)(nil),                     // 27: runthread.v1.IntensityTarget
	(*ImportedActivity)(nil),                    // 28: runthread.v1.ImportedActivity
	(*WorkoutMatch)(nil),                        // 29: runthread.v1.WorkoutMatch
	(*WorkoutResult)(nil),                       // 30: runthread.v1.WorkoutResult
	(*AdaptationEvent)(nil),                     // 31: runthread.v1.AdaptationEvent
	(*PlanChange)(nil),                          // 32: runthread.v1.PlanChange
	(*timestamppb.Timestamp)(nil),               // 33: google.protobuf.Timestamp
}
var file_runthread_v1_runthread_proto_depIdxs = []int32{
	25, // 0: runthread.v1.GetCurrentPlanWeekResponse.plan_week:type_name -> runthread.v1.PlanWeek
	28, // 1: runthread.v1.GetCurrentPlanWeekResponse.imported_activities:type_name -> runthread.v1.ImportedActivity
	29, // 2: runthread.v1.GetCurrentPlanWeekResponse.workout_matches:type_name -> runthread.v1.WorkoutMatch
	30, // 3: runthread.v1.GetCurrentPlanWeekResponse.workout_results:type_name -> runthread.v1.WorkoutResult
	31, // 4: runthread.v1.GetCurrentPlanWeekResponse.adaptation_events:type_name -> runthread.v1.AdaptationEvent
	23, // 5: runthread.v1.CompleteImportedActivityRequest.athlete_profile:type_name -> runthread.v1.AthleteProfile
	24, // 6: runthread.v1.CompleteImportedActivityRequest.training_goal:type_name -> runthread.v1.TrainingGoal
	28, // 7: runthread.v1.CompleteImportedActivityRequest.imported_activity:type_name -> runthread.v1.ImportedActivity
	11, // 8: runthread.v1.CompleteImportedActivityRequest.outcome:type_name -> runthread.v1.WorkoutOutcome
	25, // 9: runthread.v1.CompleteImportedActivityResponse.plan_week:type_name -> runthread.v1.PlanWeek
	28, // 10: runthread.v1.CompleteImportedActivityResponse.imported_activity:type_name -> runthread.v1.ImportedActivity
	29, // 11: runthread.v1.CompleteImportedActivityResponse.workout_match:type_name -> runthread.v1.WorkoutMatch
	26, // 12: runthread.v1.CompleteImportedActivityResponse.updated_workout:type_name -> runthread.v1.PlannedWorkout
	30, // 13: runthread.v1.CompleteImportedActivityResponse.workout_result:type_name -> runthread.v1.WorkoutResult
	31, // 14: runthread.v1.CompleteImportedActivityResponse.adaptation_event:type_name -> runthread.v1.AdaptationEvent
	1,  // 15: runthread.v1.GetProviderConnectionStatusRequest.provider:type_name -> runthread.v1.Provider
	22, // 16: runthread.v1.GetProviderConnectionStatusResponse.connection:type_name -> runthread.v1.ProviderConnection
	1,  // 17: runthread.v1.StartProviderConnectionRequest.provider:type_name -> runthread.v1.Provider
	22, // 18: runthread.v1.StartProviderConnectionResponse.connection:type_name -> runthread.v1.ProviderConnection
	1,  // 19: runthread.v1.ProviderConnection.provider:type_name -> runthread.v1.Provider
	2,  // 20: runthread.v1.ProviderConnection.status:type_name -> runthread.v1.ProviderConnectionStatus
	33, // 21: runthread.v1.ProviderConnection.connected_at:type_name -> google.protobuf.Timestamp
	33, // 22: runthread.v1.ProviderConnection.disconnected_at:type_name -> google.protobuf.Timestamp
	33, // 23: runthread.v1.ProviderConnection.last_sync_at:type_name -> google.protobuf.Timestamp
	0,  // 24: runthread.v1.AthleteProfile.experience_level:type_name -> runthread.v1.ExperienceLevel
	3,  // 25: runthread.v1.TrainingGoal.type:type_name -> runthread.v1.GoalType
	4,  // 26: runthread.v1.PlanWeek.focus:type_name -> runthread.v1.WeekFocus
	26, // 27: runthread.v1.PlanWeek.workouts:type_name -> runthread.v1.PlannedWorkout
	5,  // 28: runthread.v1.PlannedWorkout.type:type_name -> runthread.v1.WorkoutType
	6,  // 29: runthread.v1.PlannedWorkout.status:type_name -> runthread.v1.PlannedWorkoutStatus
	27, // 30: runthread.v1.PlannedWorkout.intensity:type_name -> runthread.v1.IntensityTarget
	7,  // 31: runthread.v1.ImportedActivity.type:type_name -> runthread.v1.ActivityType
	33, // 32: runthread.v1.ImportedActivity.started_at:type_name -> google.protobuf.Timestamp
	8,  // 33: runthread.v1.WorkoutMatch.status:type_name -> runthread.v1.WorkoutMatchStatus
	9,  // 34: runthread.v1.WorkoutMatch.confidence:type_name -> runthread.v1.MatchConfidence
	10, // 35: runthread.v1.WorkoutMatch.matched_by:type_name -> runthread.v1.MatchSource
	33, // 36: runthread.v1.WorkoutMatch.matched_at:type_name -> google.protobuf.Timestamp
	11, // 37: runthread.v1.WorkoutResult.outcome:type_name -> runthread.v1.WorkoutOutcome
	33, // 38: runthread.v1.WorkoutResult.completed_at:type_name -> google.protobuf.Timestamp
	12, // 39: runthread.v1.AdaptationEvent.type:type_name -> runthread.v1.AdaptationType
	33, // 40: runthread.v1.AdaptationEvent.created_at:type_name -> google.protobuf.Timestamp
	32, // 41: runthread.v1.AdaptationEvent.changes:type_name -> runthread.v1.PlanChange
	13, // 42: runthread.v1.PlanChange.type:type_name -> runthread.v1.PlanChangeType
	14, // 43: runthread.v1.RunthreadService.GetCurrentPlanWeek:input_type -> runthread.v1.GetCurrentPlanWeekRequest
	18, // 44: runthread.v1.RunthreadService.GetProviderConnectionStatus:input_type -> runthread.v1.GetProviderConnectionStatusRequest
	20, // 45: runthread.v1.RunthreadService.StartProviderConnection:input_type -> runthread.v1.StartProviderConnectionRequest
	16, // 46: runthread.v1.RunthreadService.CompleteImportedActivity:input_type -> runthread.v1.CompleteImportedActivityRequest
	15, // 47: runthread.v1.RunthreadService.GetCurrentPlanWeek:output_type -> runthread.v1.GetCurrentPlanWeekResponse
	19, // 48: runthread.v1.RunthreadService.GetProviderConnectionStatus:output_type -> runthread.v1.GetProviderConnectionStatusResponse
	21, // 49: runthread.v1.RunthreadService.StartProviderConnection:output_type -> runthread.v1.StartProviderConnectionResponse
	17, // 50: runthread.v1.RunthreadService.CompleteImportedActivity:output_type -> runthread.v1.CompleteImportedActivityResponse
	47, // [47:51] is the sub-list for method output_type
	43, // [43:47] is the sub-list for method input_type
	43, // [43:43] is the sub-list for extension type_name
	43, // [43:43] is the sub-list for extension extendee
	0,  // [0:43] is the sub-list for field type_name
}

func init() { file_runthread_v1_runthread_proto_init() }
func file_runthread_v1_runthread_proto_init() {
	if File_runthread_v1_runthread_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runthread_v1_runthread_proto_rawDesc), len(file_runthread_v1_runthread_proto_rawDesc)),
			NumEnums:      14,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runthread_v1_runthread_proto_goTypes,
		DependencyIndexes: file_runthread_v1_runthread_proto_depIdxs,
		EnumInfos:         file_runthread_v1_runthread_proto_enumTypes,
		MessageInfos:      file_runthread_v1_runthread_proto_msgTypes,
	}.Build()
	File_runthread_v1_runthread_proto = out.File
	file_runthread_v1_runthread_proto_goTypes = nil
	file_runthread_v1_runthread_proto_depIdxs = nil
}
