// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: adaptation_event_changes.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAdaptationEventChange = `-- name: CreateAdaptationEventChange :one
INSERT INTO adaptation_event_changes (
    id,
    adaptation_event_id,
    planned_workout_id,
    type,
    description,
    position
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, adaptation_event_id, planned_workout_id, type, description, position
`

type CreateAdaptationEventChangeParams struct {
	ID                uuid.UUID     `json:"id"`
	AdaptationEventID uuid.UUID     `json:"adaptation_event_id"`
	PlannedWorkoutID  uuid.NullUUID `json:"planned_workout_id"`
	Type              string        `json:"type"`
	Description       string        `json:"description"`
	Position          int32         `json:"position"`
}

func (q *Queries) CreateAdaptationEventChange(ctx context.Context, arg CreateAdaptationEventChangeParams) (AdaptationEventChange, error) {
	row := q.db.QueryRowContext(ctx, createAdaptationEventChange,
		arg.ID,
		arg.AdaptationEventID,
		arg.PlannedWorkoutID,
		arg.Type,
		arg.Description,
		arg.Position,
	)
	var i AdaptationEventChange
	err := row.Scan(
		&i.ID,
		&i.AdaptationEventID,
		&i.PlannedWorkoutID,
		&i.Type,
		&i.Description,
		&i.Position,
	)
	return i, err
}

const deleteAdaptationEventChanges = `-- name: DeleteAdaptationEventChanges :exec
DELETE FROM adaptation_event_changes
WHERE adaptation_event_id = $1
`

func (q *Queries) DeleteAdaptationEventChanges(ctx context.Context, adaptationEventID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAdaptationEventChanges, adaptationEventID)
	return err
}

const listAdaptationEventChanges = `-- name: ListAdaptationEventChanges :many
SELECT id, adaptation_event_id, planned_workout_id, type, description, position
FROM adaptation_event_changes
WHERE adaptation_event_id = $1
ORDER BY position, id
`

func (q *Queries) ListAdaptationEventChanges(ctx context.Context, adaptationEventID uuid.UUID) ([]AdaptationEventChange, error) {
	rows, err := q.db.QueryContext(ctx, listAdaptationEventChanges, adaptationEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdaptationEventChange
	for rows.Next() {
		var i AdaptationEventChange
		if err := rows.Scan(
			&i.ID,
			&i.AdaptationEventID,
			&i.PlannedWorkoutID,
			&i.Type,
			&i.Description,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
