// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: adaptation_events.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAdaptationEvent = `-- name: CreateAdaptationEvent :one
INSERT INTO adaptation_events (
    id,
    plan_id,
    athlete_id,
    type,
    reason,
    summary,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, plan_id, athlete_id, type, reason, summary, created_at
`

type CreateAdaptationEventParams struct {
	ID        uuid.UUID `json:"id"`
	PlanID    uuid.UUID `json:"plan_id"`
	AthleteID uuid.UUID `json:"athlete_id"`
	Type      string    `json:"type"`
	Reason    string    `json:"reason"`
	Summary   string    `json:"summary"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateAdaptationEvent(ctx context.Context, arg CreateAdaptationEventParams) (AdaptationEvent, error) {
	row := q.db.QueryRowContext(ctx, createAdaptationEvent,
		arg.ID,
		arg.PlanID,
		arg.AthleteID,
		arg.Type,
		arg.Reason,
		arg.Summary,
		arg.CreatedAt,
	)
	var i AdaptationEvent
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.AthleteID,
		&i.Type,
		&i.Reason,
		&i.Summary,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAdaptationEvent = `-- name: DeleteAdaptationEvent :exec
DELETE FROM adaptation_events
WHERE id = $1
`

func (q *Queries) DeleteAdaptationEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAdaptationEvent, id)
	return err
}

const getAdaptationEvent = `-- name: GetAdaptationEvent :one
SELECT id, plan_id, athlete_id, type, reason, summary, created_at
FROM adaptation_events
WHERE id = $1
`

func (q *Queries) GetAdaptationEvent(ctx context.Context, id uuid.UUID) (AdaptationEvent, error) {
	row := q.db.QueryRowContext(ctx, getAdaptationEvent, id)
	var i AdaptationEvent
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.AthleteID,
		&i.Type,
		&i.Reason,
		&i.Summary,
		&i.CreatedAt,
	)
	return i, err
}

const listAdaptationEventsByAthlete = `-- name: ListAdaptationEventsByAthlete :many
SELECT id, plan_id, athlete_id, type, reason, summary, created_at
FROM adaptation_events
WHERE athlete_id = $1
ORDER BY created_at DESC, id
`

func (q *Queries) ListAdaptationEventsByAthlete(ctx context.Context, athleteID uuid.UUID) ([]AdaptationEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAdaptationEventsByAthlete, athleteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdaptationEvent
	for rows.Next() {
		var i AdaptationEvent
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.AthleteID,
			&i.Type,
			&i.Reason,
			&i.Summary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdaptationEventsByPlan = `-- name: ListAdaptationEventsByPlan :many
SELECT id, plan_id, athlete_id, type, reason, summary, created_at
FROM adaptation_events
WHERE plan_id = $1
ORDER BY created_at DESC, id
`

func (q *Queries) ListAdaptationEventsByPlan(ctx context.Context, planID uuid.UUID) ([]AdaptationEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAdaptationEventsByPlan, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdaptationEvent
	for rows.Next() {
		var i AdaptationEvent
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.AthleteID,
			&i.Type,
			&i.Reason,
			&i.Summary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdaptationEvent = `-- name: UpdateAdaptationEvent :one
UPDATE adaptation_events
SET
    plan_id = $1,
    athlete_id = $2,
    type = $3,
    reason = $4,
    summary = $5,
    created_at = $6
WHERE id = $7
RETURNING id, plan_id, athlete_id, type, reason, summary, created_at
`

type UpdateAdaptationEventParams struct {
	PlanID    uuid.UUID `json:"plan_id"`
	AthleteID uuid.UUID `json:"athlete_id"`
	Type      string    `json:"type"`
	Reason    string    `json:"reason"`
	Summary   string    `json:"summary"`
	CreatedAt time.Time `json:"created_at"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) UpdateAdaptationEvent(ctx context.Context, arg UpdateAdaptationEventParams) (AdaptationEvent, error) {
	row := q.db.QueryRowContext(ctx, updateAdaptationEvent,
		arg.PlanID,
		arg.AthleteID,
		arg.Type,
		arg.Reason,
		arg.Summary,
		arg.CreatedAt,
		arg.ID,
	)
	var i AdaptationEvent
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.AthleteID,
		&i.Type,
		&i.Reason,
		&i.Summary,
		&i.CreatedAt,
	)
	return i, err
}
