// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: athlete_profiles.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createAthleteProfile = `-- name: CreateAthleteProfile :one
INSERT INTO athlete_profiles (
    id,
    display_name,
    experience_level,
    current_weekly_distance_meters,
    preferred_run_days,
    constraints
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, display_name, experience_level, current_weekly_distance_meters, preferred_run_days, constraints, created_at, updated_at
`

type CreateAthleteProfileParams struct {
	ID                          uuid.UUID      `json:"id"`
	DisplayName                 sql.NullString `json:"display_name"`
	ExperienceLevel             sql.NullString `json:"experience_level"`
	CurrentWeeklyDistanceMeters float64        `json:"current_weekly_distance_meters"`
	PreferredRunDays            []int16        `json:"preferred_run_days"`
	Constraints                 []string       `json:"constraints"`
}

func (q *Queries) CreateAthleteProfile(ctx context.Context, arg CreateAthleteProfileParams) (AthleteProfile, error) {
	row := q.db.QueryRowContext(ctx, createAthleteProfile,
		arg.ID,
		arg.DisplayName,
		arg.ExperienceLevel,
		arg.CurrentWeeklyDistanceMeters,
		pq.Array(arg.PreferredRunDays),
		pq.Array(arg.Constraints),
	)
	var i AthleteProfile
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.ExperienceLevel,
		&i.CurrentWeeklyDistanceMeters,
		pq.Array(&i.PreferredRunDays),
		pq.Array(&i.Constraints),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAthleteProfile = `-- name: DeleteAthleteProfile :exec
DELETE FROM athlete_profiles
WHERE id = $1
`

func (q *Queries) DeleteAthleteProfile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAthleteProfile, id)
	return err
}

const getAthleteProfile = `-- name: GetAthleteProfile :one
SELECT id, display_name, experience_level, current_weekly_distance_meters, preferred_run_days, constraints, created_at, updated_at
FROM athlete_profiles
WHERE id = $1
`

func (q *Queries) GetAthleteProfile(ctx context.Context, id uuid.UUID) (AthleteProfile, error) {
	row := q.db.QueryRowContext(ctx, getAthleteProfile, id)
	var i AthleteProfile
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.ExperienceLevel,
		&i.CurrentWeeklyDistanceMeters,
		pq.Array(&i.PreferredRunDays),
		pq.Array(&i.Constraints),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAthleteProfile = `-- name: UpdateAthleteProfile :one
UPDATE athlete_profiles
SET
    display_name = $1,
    experience_level = $2,
    current_weekly_distance_meters = $3,
    preferred_run_days = $4,
    constraints = $5,
    updated_at = now()
WHERE id = $6
RETURNING id, display_name, experience_level, current_weekly_distance_meters, preferred_run_days, constraints, created_at, updated_at
`

type UpdateAthleteProfileParams struct {
	DisplayName                 sql.NullString `json:"display_name"`
	ExperienceLevel             sql.NullString `json:"experience_level"`
	CurrentWeeklyDistanceMeters float64        `json:"current_weekly_distance_meters"`
	PreferredRunDays            []int16        `json:"preferred_run_days"`
	Constraints                 []string       `json:"constraints"`
	ID                          uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateAthleteProfile(ctx context.Context, arg UpdateAthleteProfileParams) (AthleteProfile, error) {
	row := q.db.QueryRowContext(ctx, updateAthleteProfile,
		arg.DisplayName,
		arg.ExperienceLevel,
		arg.CurrentWeeklyDistanceMeters,
		pq.Array(arg.PreferredRunDays),
		pq.Array(arg.Constraints),
		arg.ID,
	)
	var i AthleteProfile
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.ExperienceLevel,
		&i.CurrentWeeklyDistanceMeters,
		pq.Array(&i.PreferredRunDays),
		pq.Array(&i.Constraints),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
