// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: imported_activities.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createImportedActivity = `-- name: CreateImportedActivity :one
INSERT INTO imported_activities (
    id,
    athlete_id,
    type,
    started_at,
    duration_seconds,
    distance_meters,
    average_pace_seconds_per_kilometer,
    average_heart_bpm
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, athlete_id, type, started_at, duration_seconds, distance_meters, average_pace_seconds_per_kilometer, average_heart_bpm, created_at
`

type CreateImportedActivityParams struct {
	ID                             uuid.UUID       `json:"id"`
	AthleteID                      uuid.UUID       `json:"athlete_id"`
	Type                           string          `json:"type"`
	StartedAt                      time.Time       `json:"started_at"`
	DurationSeconds                int32           `json:"duration_seconds"`
	DistanceMeters                 sql.NullFloat64 `json:"distance_meters"`
	AveragePaceSecondsPerKilometer sql.NullInt32   `json:"average_pace_seconds_per_kilometer"`
	AverageHeartBpm                sql.NullInt32   `json:"average_heart_bpm"`
}

func (q *Queries) CreateImportedActivity(ctx context.Context, arg CreateImportedActivityParams) (ImportedActivity, error) {
	row := q.db.QueryRowContext(ctx, createImportedActivity,
		arg.ID,
		arg.AthleteID,
		arg.Type,
		arg.StartedAt,
		arg.DurationSeconds,
		arg.DistanceMeters,
		arg.AveragePaceSecondsPerKilometer,
		arg.AverageHeartBpm,
	)
	var i ImportedActivity
	err := row.Scan(
		&i.ID,
		&i.AthleteID,
		&i.Type,
		&i.StartedAt,
		&i.DurationSeconds,
		&i.DistanceMeters,
		&i.AveragePaceSecondsPerKilometer,
		&i.AverageHeartBpm,
		&i.CreatedAt,
	)
	return i, err
}

const deleteImportedActivity = `-- name: DeleteImportedActivity :exec
DELETE FROM imported_activities
WHERE id = $1
`

func (q *Queries) DeleteImportedActivity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteImportedActivity, id)
	return err
}

const getImportedActivity = `-- name: GetImportedActivity :one
SELECT id, athlete_id, type, started_at, duration_seconds, distance_meters, average_pace_seconds_per_kilometer, average_heart_bpm, created_at
FROM imported_activities
WHERE id = $1
`

func (q *Queries) GetImportedActivity(ctx context.Context, id uuid.UUID) (ImportedActivity, error) {
	row := q.db.QueryRowContext(ctx, getImportedActivity, id)
	var i ImportedActivity
	err := row.Scan(
		&i.ID,
		&i.AthleteID,
		&i.Type,
		&i.StartedAt,
		&i.DurationSeconds,
		&i.DistanceMeters,
		&i.AveragePaceSecondsPerKilometer,
		&i.AverageHeartBpm,
		&i.CreatedAt,
	)
	return i, err
}

const listImportedActivitiesByAthlete = `-- name: ListImportedActivitiesByAthlete :many
SELECT id, athlete_id, type, started_at, duration_seconds, distance_meters, average_pace_seconds_per_kilometer, average_heart_bpm, created_at
FROM imported_activities
WHERE athlete_id = $1
ORDER BY started_at DESC, id
`

func (q *Queries) ListImportedActivitiesByAthlete(ctx context.Context, athleteID uuid.UUID) ([]ImportedActivity, error) {
	rows, err := q.db.QueryContext(ctx, listImportedActivitiesByAthlete, athleteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportedActivity
	for rows.Next() {
		var i ImportedActivity
		if err := rows.Scan(
			&i.ID,
			&i.AthleteID,
			&i.Type,
			&i.StartedAt,
			&i.DurationSeconds,
			&i.DistanceMeters,
			&i.AveragePaceSecondsPerKilometer,
			&i.AverageHeartBpm,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImportedActivity = `-- name: UpdateImportedActivity :one
UPDATE imported_activities
SET
    athlete_id = $1,
    type = $2,
    started_at = $3,
    duration_seconds = $4,
    distance_meters = $5,
    average_pace_seconds_per_kilometer = $6,
    average_heart_bpm = $7
WHERE id = $8
RETURNING id, athlete_id, type, started_at, duration_seconds, distance_meters, average_pace_seconds_per_kilometer, average_heart_bpm, created_at
`

type UpdateImportedActivityParams struct {
	AthleteID                      uuid.UUID       `json:"athlete_id"`
	Type                           string          `json:"type"`
	StartedAt                      time.Time       `json:"started_at"`
	DurationSeconds                int32           `json:"duration_seconds"`
	DistanceMeters                 sql.NullFloat64 `json:"distance_meters"`
	AveragePaceSecondsPerKilometer sql.NullInt32   `json:"average_pace_seconds_per_kilometer"`
	AverageHeartBpm                sql.NullInt32   `json:"average_heart_bpm"`
	ID                             uuid.UUID       `json:"id"`
}

func (q *Queries) UpdateImportedActivity(ctx context.Context, arg UpdateImportedActivityParams) (ImportedActivity, error) {
	row := q.db.QueryRowContext(ctx, updateImportedActivity,
		arg.AthleteID,
		arg.Type,
		arg.StartedAt,
		arg.DurationSeconds,
		arg.DistanceMeters,
		arg.AveragePaceSecondsPerKilometer,
		arg.AverageHeartBpm,
		arg.ID,
	)
	var i ImportedActivity
	err := row.Scan(
		&i.ID,
		&i.AthleteID,
		&i.Type,
		&i.StartedAt,
		&i.DurationSeconds,
		&i.DistanceMeters,
		&i.AveragePaceSecondsPerKilometer,
		&i.AverageHeartBpm,
		&i.CreatedAt,
	)
	return i, err
}
