// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type AdaptationEvent struct {
	ID        uuid.UUID `json:"id"`
	PlanID    uuid.UUID `json:"plan_id"`
	AthleteID uuid.UUID `json:"athlete_id"`
	Type      string    `json:"type"`
	Reason    string    `json:"reason"`
	Summary   string    `json:"summary"`
	CreatedAt time.Time `json:"created_at"`
}

type AdaptationEventChange struct {
	ID                uuid.UUID     `json:"id"`
	AdaptationEventID uuid.UUID     `json:"adaptation_event_id"`
	PlannedWorkoutID  uuid.NullUUID `json:"planned_workout_id"`
	Type              string        `json:"type"`
	Description       string        `json:"description"`
	Position          int32         `json:"position"`
}

type AthleteProfile struct {
	ID                          uuid.UUID      `json:"id"`
	DisplayName                 sql.NullString `json:"display_name"`
	ExperienceLevel             sql.NullString `json:"experience_level"`
	CurrentWeeklyDistanceMeters float64        `json:"current_weekly_distance_meters"`
	PreferredRunDays            []int64        `json:"preferred_run_days"`
	Constraints                 []string       `json:"constraints"`
	CreatedAt                   time.Time      `json:"created_at"`
	UpdatedAt                   time.Time      `json:"updated_at"`
}

type ImportedActivity struct {
	ID                             uuid.UUID       `json:"id"`
	AthleteID                      uuid.UUID       `json:"athlete_id"`
	Type                           string          `json:"type"`
	StartedAt                      time.Time       `json:"started_at"`
	DurationSeconds                int32           `json:"duration_seconds"`
	DistanceMeters                 sql.NullFloat64 `json:"distance_meters"`
	AveragePaceSecondsPerKilometer sql.NullInt32   `json:"average_pace_seconds_per_kilometer"`
	AverageHeartBpm                sql.NullInt32   `json:"average_heart_bpm"`
	CreatedAt                      time.Time       `json:"created_at"`
}

type PlanWeek struct {
	ID        uuid.UUID      `json:"id"`
	AthleteID uuid.UUID      `json:"athlete_id"`
	GoalID    uuid.NullUUID  `json:"goal_id"`
	PlanID    uuid.UUID      `json:"plan_id"`
	WeekIndex int32          `json:"week_index"`
	StartsOn  time.Time      `json:"starts_on"`
	Focus     sql.NullString `json:"focus"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type PlannedWorkout struct {
	ID                    uuid.UUID       `json:"id"`
	PlanWeekID            uuid.UUID       `json:"plan_week_id"`
	PlanID                uuid.UUID       `json:"plan_id"`
	ScheduledFor          time.Time       `json:"scheduled_for"`
	Type                  string          `json:"type"`
	Status                string          `json:"status"`
	TargetDistanceMeters  sql.NullFloat64 `json:"target_distance_meters"`
	TargetDurationSeconds sql.NullInt32   `json:"target_duration_seconds"`
	IntensityKind         sql.NullString  `json:"intensity_kind"`
	IntensityDescription  sql.NullString  `json:"intensity_description"`
	Notes                 sql.NullString  `json:"notes"`
	CreatedAt             time.Time       `json:"created_at"`
	UpdatedAt             time.Time       `json:"updated_at"`
}

type ProviderActivity struct {
	ID                   uuid.UUID      `json:"id"`
	ProviderConnectionID uuid.UUID      `json:"provider_connection_id"`
	AthleteID            uuid.UUID      `json:"athlete_id"`
	ImportedActivityID   uuid.NullUUID  `json:"imported_activity_id"`
	Provider             string         `json:"provider"`
	ProviderActivityID   string         `json:"provider_activity_id"`
	ProviderActivityType sql.NullString `json:"provider_activity_type"`
	StartedAt            sql.NullTime   `json:"started_at"`
	Status               string         `json:"status"`
	FirstSeenAt          time.Time      `json:"first_seen_at"`
	LastSyncedAt         sql.NullTime   `json:"last_synced_at"`
	LastError            sql.NullString `json:"last_error"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
}

type ProviderActivityPayload struct {
	ID                 uuid.UUID       `json:"id"`
	ProviderActivityID uuid.UUID       `json:"provider_activity_id"`
	Payload            json.RawMessage `json:"payload"`
	PayloadKind        string          `json:"payload_kind"`
	ReceivedAt         time.Time       `json:"received_at"`
}

type ProviderConnection struct {
	ID               uuid.UUID      `json:"id"`
	AthleteID        uuid.UUID      `json:"athlete_id"`
	Provider         string         `json:"provider"`
	ProviderUserID   sql.NullString `json:"provider_user_id"`
	Status           string         `json:"status"`
	ConnectedAt      sql.NullTime   `json:"connected_at"`
	DisconnectedAt   sql.NullTime   `json:"disconnected_at"`
	LastSyncAt       sql.NullTime   `json:"last_sync_at"`
	LastImportCursor sql.NullString `json:"last_import_cursor"`
	TokenReference   sql.NullString `json:"token_reference"`
	TokenExpiresAt   sql.NullTime   `json:"token_expires_at"`
	LastError        sql.NullString `json:"last_error"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

type ProviderImportEvent struct {
	ID                   uuid.UUID      `json:"id"`
	ProviderConnectionID uuid.NullUUID  `json:"provider_connection_id"`
	ProviderActivityID   uuid.NullUUID  `json:"provider_activity_id"`
	Provider             string         `json:"provider"`
	EventType            string         `json:"event_type"`
	DeliveryID           sql.NullString `json:"delivery_id"`
	Status               string         `json:"status"`
	ReceivedAt           time.Time      `json:"received_at"`
	ProcessedAt          sql.NullTime   `json:"processed_at"`
	Error                sql.NullString `json:"error"`
}

type TrainingGoal struct {
	ID                    uuid.UUID       `json:"id"`
	AthleteID             uuid.UUID       `json:"athlete_id"`
	Type                  string          `json:"type"`
	TargetDate            sql.NullTime    `json:"target_date"`
	TargetDistanceMeters  sql.NullFloat64 `json:"target_distance_meters"`
	TargetDurationSeconds sql.NullInt32   `json:"target_duration_seconds"`
	Notes                 sql.NullString  `json:"notes"`
	CreatedAt             time.Time       `json:"created_at"`
	UpdatedAt             time.Time       `json:"updated_at"`
}

type WorkoutMatch struct {
	ID                 uuid.UUID      `json:"id"`
	PlannedWorkoutID   uuid.UUID      `json:"planned_workout_id"`
	ImportedActivityID uuid.UUID      `json:"imported_activity_id"`
	Status             string         `json:"status"`
	Confidence         string         `json:"confidence"`
	MatchedBy          string         `json:"matched_by"`
	MatchedAt          time.Time      `json:"matched_at"`
	Notes              sql.NullString `json:"notes"`
	CreatedAt          time.Time      `json:"created_at"`
}

type WorkoutResult struct {
	ID                 uuid.UUID       `json:"id"`
	PlannedWorkoutID   uuid.UUID       `json:"planned_workout_id"`
	ImportedActivityID uuid.NullUUID   `json:"imported_activity_id"`
	Outcome            string          `json:"outcome"`
	CompletedAt        sql.NullTime    `json:"completed_at"`
	DistanceMeters     sql.NullFloat64 `json:"distance_meters"`
	DurationSeconds    sql.NullInt32   `json:"duration_seconds"`
	Notes              sql.NullString  `json:"notes"`
	CreatedAt          time.Time       `json:"created_at"`
}
