// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plan_weeks.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPlanWeek = `-- name: CreatePlanWeek :one
INSERT INTO plan_weeks (
    id,
    athlete_id,
    goal_id,
    plan_id,
    week_index,
    starts_on,
    focus
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, athlete_id, goal_id, plan_id, week_index, starts_on, focus, created_at, updated_at
`

type CreatePlanWeekParams struct {
	ID        uuid.UUID      `json:"id"`
	AthleteID uuid.UUID      `json:"athlete_id"`
	GoalID    uuid.NullUUID  `json:"goal_id"`
	PlanID    uuid.UUID      `json:"plan_id"`
	WeekIndex int32          `json:"week_index"`
	StartsOn  time.Time      `json:"starts_on"`
	Focus     sql.NullString `json:"focus"`
}

func (q *Queries) CreatePlanWeek(ctx context.Context, arg CreatePlanWeekParams) (PlanWeek, error) {
	row := q.db.QueryRowContext(ctx, createPlanWeek,
		arg.ID,
		arg.AthleteID,
		arg.GoalID,
		arg.PlanID,
		arg.WeekIndex,
		arg.StartsOn,
		arg.Focus,
	)
	var i PlanWeek
	err := row.Scan(
		&i.ID,
		&i.AthleteID,
		&i.GoalID,
		&i.PlanID,
		&i.WeekIndex,
		&i.StartsOn,
		&i.Focus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlanWeek = `-- name: DeletePlanWeek :exec
DELETE FROM plan_weeks
WHERE id = $1
`

func (q *Queries) DeletePlanWeek(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePlanWeek, id)
	return err
}

const getPlanWeek = `-- name: GetPlanWeek :one
SELECT id, athlete_id, goal_id, plan_id, week_index, starts_on, focus, created_at, updated_at
FROM plan_weeks
WHERE id = $1
`

func (q *Queries) GetPlanWeek(ctx context.Context, id uuid.UUID) (PlanWeek, error) {
	row := q.db.QueryRowContext(ctx, getPlanWeek, id)
	var i PlanWeek
	err := row.Scan(
		&i.ID,
		&i.AthleteID,
		&i.GoalID,
		&i.PlanID,
		&i.WeekIndex,
		&i.StartsOn,
		&i.Focus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlanWeeksByAthlete = `-- name: ListPlanWeeksByAthlete :many
SELECT id, athlete_id, goal_id, plan_id, week_index, starts_on, focus, created_at, updated_at
FROM plan_weeks
WHERE athlete_id = $1
ORDER BY starts_on DESC, week_index DESC
`

func (q *Queries) ListPlanWeeksByAthlete(ctx context.Context, athleteID uuid.UUID) ([]PlanWeek, error) {
	rows, err := q.db.QueryContext(ctx, listPlanWeeksByAthlete, athleteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanWeek
	for rows.Next() {
		var i PlanWeek
		if err := rows.Scan(
			&i.ID,
			&i.AthleteID,
			&i.GoalID,
			&i.PlanID,
			&i.WeekIndex,
			&i.StartsOn,
			&i.Focus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanWeeksByPlan = `-- name: ListPlanWeeksByPlan :many
SELECT id, athlete_id, goal_id, plan_id, week_index, starts_on, focus, created_at, updated_at
FROM plan_weeks
WHERE plan_id = $1
ORDER BY week_index
`

func (q *Queries) ListPlanWeeksByPlan(ctx context.Context, planID uuid.UUID) ([]PlanWeek, error) {
	rows, err := q.db.QueryContext(ctx, listPlanWeeksByPlan, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanWeek
	for rows.Next() {
		var i PlanWeek
		if err := rows.Scan(
			&i.ID,
			&i.AthleteID,
			&i.GoalID,
			&i.PlanID,
			&i.WeekIndex,
			&i.StartsOn,
			&i.Focus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlanWeek = `-- name: UpdatePlanWeek :one
UPDATE plan_weeks
SET
    goal_id = $1,
    week_index = $2,
    starts_on = $3,
    focus = $4,
    updated_at = now()
WHERE id = $5
RETURNING id, athlete_id, goal_id, plan_id, week_index, starts_on, focus, created_at, updated_at
`

type UpdatePlanWeekParams struct {
	GoalID    uuid.NullUUID  `json:"goal_id"`
	WeekIndex int32          `json:"week_index"`
	StartsOn  time.Time      `json:"starts_on"`
	Focus     sql.NullString `json:"focus"`
	ID        uuid.UUID      `json:"id"`
}

func (q *Queries) UpdatePlanWeek(ctx context.Context, arg UpdatePlanWeekParams) (PlanWeek, error) {
	row := q.db.QueryRowContext(ctx, updatePlanWeek,
		arg.GoalID,
		arg.WeekIndex,
		arg.StartsOn,
		arg.Focus,
		arg.ID,
	)
	var i PlanWeek
	err := row.Scan(
		&i.ID,
		&i.AthleteID,
		&i.GoalID,
		&i.PlanID,
		&i.WeekIndex,
		&i.StartsOn,
		&i.Focus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
