// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: planned_workouts.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPlannedWorkout = `-- name: CreatePlannedWorkout :one
INSERT INTO planned_workouts (
    id,
    plan_week_id,
    plan_id,
    scheduled_for,
    type,
    status,
    target_distance_meters,
    target_duration_seconds,
    intensity_kind,
    intensity_description,
    notes
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING id, plan_week_id, plan_id, scheduled_for, type, status, target_distance_meters, target_duration_seconds, intensity_kind, intensity_description, notes, created_at, updated_at
`

type CreatePlannedWorkoutParams struct {
	ID                    uuid.UUID       `json:"id"`
	PlanWeekID            uuid.UUID       `json:"plan_week_id"`
	PlanID                uuid.UUID       `json:"plan_id"`
	ScheduledFor          time.Time       `json:"scheduled_for"`
	Type                  string          `json:"type"`
	Status                string          `json:"status"`
	TargetDistanceMeters  sql.NullFloat64 `json:"target_distance_meters"`
	TargetDurationSeconds sql.NullInt32   `json:"target_duration_seconds"`
	IntensityKind         sql.NullString  `json:"intensity_kind"`
	IntensityDescription  sql.NullString  `json:"intensity_description"`
	Notes                 sql.NullString  `json:"notes"`
}

func (q *Queries) CreatePlannedWorkout(ctx context.Context, arg CreatePlannedWorkoutParams) (PlannedWorkout, error) {
	row := q.db.QueryRowContext(ctx, createPlannedWorkout,
		arg.ID,
		arg.PlanWeekID,
		arg.PlanID,
		arg.ScheduledFor,
		arg.Type,
		arg.Status,
		arg.TargetDistanceMeters,
		arg.TargetDurationSeconds,
		arg.IntensityKind,
		arg.IntensityDescription,
		arg.Notes,
	)
	var i PlannedWorkout
	err := row.Scan(
		&i.ID,
		&i.PlanWeekID,
		&i.PlanID,
		&i.ScheduledFor,
		&i.Type,
		&i.Status,
		&i.TargetDistanceMeters,
		&i.TargetDurationSeconds,
		&i.IntensityKind,
		&i.IntensityDescription,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlannedWorkout = `-- name: DeletePlannedWorkout :exec
DELETE FROM planned_workouts
WHERE id = $1
`

func (q *Queries) DeletePlannedWorkout(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePlannedWorkout, id)
	return err
}

const getPlannedWorkout = `-- name: GetPlannedWorkout :one
SELECT id, plan_week_id, plan_id, scheduled_for, type, status, target_distance_meters, target_duration_seconds, intensity_kind, intensity_description, notes, created_at, updated_at
FROM planned_workouts
WHERE id = $1
`

func (q *Queries) GetPlannedWorkout(ctx context.Context, id uuid.UUID) (PlannedWorkout, error) {
	row := q.db.QueryRowContext(ctx, getPlannedWorkout, id)
	var i PlannedWorkout
	err := row.Scan(
		&i.ID,
		&i.PlanWeekID,
		&i.PlanID,
		&i.ScheduledFor,
		&i.Type,
		&i.Status,
		&i.TargetDistanceMeters,
		&i.TargetDurationSeconds,
		&i.IntensityKind,
		&i.IntensityDescription,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlannedWorkoutsByPlan = `-- name: ListPlannedWorkoutsByPlan :many
SELECT id, plan_week_id, plan_id, scheduled_for, type, status, target_distance_meters, target_duration_seconds, intensity_kind, intensity_description, notes, created_at, updated_at
FROM planned_workouts
WHERE plan_id = $1
ORDER BY scheduled_for, id
`

func (q *Queries) ListPlannedWorkoutsByPlan(ctx context.Context, planID uuid.UUID) ([]PlannedWorkout, error) {
	rows, err := q.db.QueryContext(ctx, listPlannedWorkoutsByPlan, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlannedWorkout
	for rows.Next() {
		var i PlannedWorkout
		if err := rows.Scan(
			&i.ID,
			&i.PlanWeekID,
			&i.PlanID,
			&i.ScheduledFor,
			&i.Type,
			&i.Status,
			&i.TargetDistanceMeters,
			&i.TargetDurationSeconds,
			&i.IntensityKind,
			&i.IntensityDescription,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlannedWorkoutsByWeek = `-- name: ListPlannedWorkoutsByWeek :many
SELECT id, plan_week_id, plan_id, scheduled_for, type, status, target_distance_meters, target_duration_seconds, intensity_kind, intensity_description, notes, created_at, updated_at
FROM planned_workouts
WHERE plan_week_id = $1
ORDER BY scheduled_for, id
`

func (q *Queries) ListPlannedWorkoutsByWeek(ctx context.Context, planWeekID uuid.UUID) ([]PlannedWorkout, error) {
	rows, err := q.db.QueryContext(ctx, listPlannedWorkoutsByWeek, planWeekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlannedWorkout
	for rows.Next() {
		var i PlannedWorkout
		if err := rows.Scan(
			&i.ID,
			&i.PlanWeekID,
			&i.PlanID,
			&i.ScheduledFor,
			&i.Type,
			&i.Status,
			&i.TargetDistanceMeters,
			&i.TargetDurationSeconds,
			&i.IntensityKind,
			&i.IntensityDescription,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlannedWorkout = `-- name: UpdatePlannedWorkout :one
UPDATE planned_workouts
SET
    scheduled_for = $1,
    type = $2,
    status = $3,
    target_distance_meters = $4,
    target_duration_seconds = $5,
    intensity_kind = $6,
    intensity_description = $7,
    notes = $8,
    updated_at = now()
WHERE id = $9
RETURNING id, plan_week_id, plan_id, scheduled_for, type, status, target_distance_meters, target_duration_seconds, intensity_kind, intensity_description, notes, created_at, updated_at
`

type UpdatePlannedWorkoutParams struct {
	ScheduledFor          time.Time       `json:"scheduled_for"`
	Type                  string          `json:"type"`
	Status                string          `json:"status"`
	TargetDistanceMeters  sql.NullFloat64 `json:"target_distance_meters"`
	TargetDurationSeconds sql.NullInt32   `json:"target_duration_seconds"`
	IntensityKind         sql.NullString  `json:"intensity_kind"`
	IntensityDescription  sql.NullString  `json:"intensity_description"`
	Notes                 sql.NullString  `json:"notes"`
	ID                    uuid.UUID       `json:"id"`
}

func (q *Queries) UpdatePlannedWorkout(ctx context.Context, arg UpdatePlannedWorkoutParams) (PlannedWorkout, error) {
	row := q.db.QueryRowContext(ctx, updatePlannedWorkout,
		arg.ScheduledFor,
		arg.Type,
		arg.Status,
		arg.TargetDistanceMeters,
		arg.TargetDurationSeconds,
		arg.IntensityKind,
		arg.IntensityDescription,
		arg.Notes,
		arg.ID,
	)
	var i PlannedWorkout
	err := row.Scan(
		&i.ID,
		&i.PlanWeekID,
		&i.PlanID,
		&i.ScheduledFor,
		&i.Type,
		&i.Status,
		&i.TargetDistanceMeters,
		&i.TargetDurationSeconds,
		&i.IntensityKind,
		&i.IntensityDescription,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlannedWorkoutStatus = `-- name: UpdatePlannedWorkoutStatus :one
UPDATE planned_workouts
SET
    status = $1,
    updated_at = now()
WHERE id = $2
RETURNING id, plan_week_id, plan_id, scheduled_for, type, status, target_distance_meters, target_duration_seconds, intensity_kind, intensity_description, notes, created_at, updated_at
`

type UpdatePlannedWorkoutStatusParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdatePlannedWorkoutStatus(ctx context.Context, arg UpdatePlannedWorkoutStatusParams) (PlannedWorkout, error) {
	row := q.db.QueryRowContext(ctx, updatePlannedWorkoutStatus, arg.Status, arg.ID)
	var i PlannedWorkout
	err := row.Scan(
		&i.ID,
		&i.PlanWeekID,
		&i.PlanID,
		&i.ScheduledFor,
		&i.Type,
		&i.Status,
		&i.TargetDistanceMeters,
		&i.TargetDurationSeconds,
		&i.IntensityKind,
		&i.IntensityDescription,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
