// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_activity_payloads.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createProviderActivityPayload = `-- name: CreateProviderActivityPayload :one
INSERT INTO provider_activity_payloads (
    id,
    provider_activity_id,
    payload,
    payload_kind,
    received_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, provider_activity_id, payload, payload_kind, received_at
`

type CreateProviderActivityPayloadParams struct {
	ID                 uuid.UUID       `json:"id"`
	ProviderActivityID uuid.UUID       `json:"provider_activity_id"`
	Payload            json.RawMessage `json:"payload"`
	PayloadKind        string          `json:"payload_kind"`
	ReceivedAt         time.Time       `json:"received_at"`
}

func (q *Queries) CreateProviderActivityPayload(ctx context.Context, arg CreateProviderActivityPayloadParams) (ProviderActivityPayload, error) {
	row := q.db.QueryRowContext(ctx, createProviderActivityPayload,
		arg.ID,
		arg.ProviderActivityID,
		arg.Payload,
		arg.PayloadKind,
		arg.ReceivedAt,
	)
	var i ProviderActivityPayload
	err := row.Scan(
		&i.ID,
		&i.ProviderActivityID,
		&i.Payload,
		&i.PayloadKind,
		&i.ReceivedAt,
	)
	return i, err
}

const getProviderActivityPayload = `-- name: GetProviderActivityPayload :one
SELECT id, provider_activity_id, payload, payload_kind, received_at
FROM provider_activity_payloads
WHERE id = $1
`

func (q *Queries) GetProviderActivityPayload(ctx context.Context, id uuid.UUID) (ProviderActivityPayload, error) {
	row := q.db.QueryRowContext(ctx, getProviderActivityPayload, id)
	var i ProviderActivityPayload
	err := row.Scan(
		&i.ID,
		&i.ProviderActivityID,
		&i.Payload,
		&i.PayloadKind,
		&i.ReceivedAt,
	)
	return i, err
}

const listProviderActivityPayloads = `-- name: ListProviderActivityPayloads :many
SELECT id, provider_activity_id, payload, payload_kind, received_at
FROM provider_activity_payloads
WHERE provider_activity_id = $1
ORDER BY received_at DESC, id
`

func (q *Queries) ListProviderActivityPayloads(ctx context.Context, providerActivityID uuid.UUID) ([]ProviderActivityPayload, error) {
	rows, err := q.db.QueryContext(ctx, listProviderActivityPayloads, providerActivityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderActivityPayload
	for rows.Next() {
		var i ProviderActivityPayload
		if err := rows.Scan(
			&i.ID,
			&i.ProviderActivityID,
			&i.Payload,
			&i.PayloadKind,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProviderActivityPayload = `-- name: UpdateProviderActivityPayload :one
UPDATE provider_activity_payloads
SET
    provider_activity_id = $1,
    payload = $2,
    payload_kind = $3,
    received_at = $4
WHERE id = $5
RETURNING id, provider_activity_id, payload, payload_kind, received_at
`

type UpdateProviderActivityPayloadParams struct {
	ProviderActivityID uuid.UUID       `json:"provider_activity_id"`
	Payload            json.RawMessage `json:"payload"`
	PayloadKind        string          `json:"payload_kind"`
	ReceivedAt         time.Time       `json:"received_at"`
	ID                 uuid.UUID       `json:"id"`
}

func (q *Queries) UpdateProviderActivityPayload(ctx context.Context, arg UpdateProviderActivityPayloadParams) (ProviderActivityPayload, error) {
	row := q.db.QueryRowContext(ctx, updateProviderActivityPayload,
		arg.ProviderActivityID,
		arg.Payload,
		arg.PayloadKind,
		arg.ReceivedAt,
		arg.ID,
	)
	var i ProviderActivityPayload
	err := row.Scan(
		&i.ID,
		&i.ProviderActivityID,
		&i.Payload,
		&i.PayloadKind,
		&i.ReceivedAt,
	)
	return i, err
}
