// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_connections.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProviderConnection = `-- name: CreateProviderConnection :one
INSERT INTO provider_connections (
    id,
    athlete_id,
    provider,
    provider_user_id,
    status,
    connected_at,
    disconnected_at,
    last_sync_at,
    last_import_cursor,
    token_reference,
    token_expires_at,
    last_error
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
RETURNING id, athlete_id, provider, provider_user_id, status, connected_at, disconnected_at, last_sync_at, last_import_cursor, token_reference, token_expires_at, last_error, created_at, updated_at
`

type CreateProviderConnectionParams struct {
	ID               uuid.UUID      `json:"id"`
	AthleteID        uuid.UUID      `json:"athlete_id"`
	Provider         string         `json:"provider"`
	ProviderUserID   sql.NullString `json:"provider_user_id"`
	Status           string         `json:"status"`
	ConnectedAt      sql.NullTime   `json:"connected_at"`
	DisconnectedAt   sql.NullTime   `json:"disconnected_at"`
	LastSyncAt       sql.NullTime   `json:"last_sync_at"`
	LastImportCursor sql.NullString `json:"last_import_cursor"`
	TokenReference   sql.NullString `json:"token_reference"`
	TokenExpiresAt   sql.NullTime   `json:"token_expires_at"`
	LastError        sql.NullString `json:"last_error"`
}

func (q *Queries) CreateProviderConnection(ctx context.Context, arg CreateProviderConnectionParams) (ProviderConnection, error) {
	row := q.db.QueryRowContext(ctx, createProviderConnection,
		arg.ID,
		arg.AthleteID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Status,
		arg.ConnectedAt,
		arg.DisconnectedAt,
		arg.LastSyncAt,
		arg.LastImportCursor,
		arg.TokenReference,
		arg.TokenExpiresAt,
		arg.LastError,
	)
	var i ProviderConnection
	err := row.Scan(
		&i.ID,
		&i.AthleteID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Status,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.LastSyncAt,
		&i.LastImportCursor,
		&i.TokenReference,
		&i.TokenExpiresAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderConnection = `-- name: GetProviderConnection :one
SELECT id, athlete_id, provider, provider_user_id, status, connected_at, disconnected_at, last_sync_at, last_import_cursor, token_reference, token_expires_at, last_error, created_at, updated_at
FROM provider_connections
WHERE id = $1
`

func (q *Queries) GetProviderConnection(ctx context.Context, id uuid.UUID) (ProviderConnection, error) {
	row := q.db.QueryRowContext(ctx, getProviderConnection, id)
	var i ProviderConnection
	err := row.Scan(
		&i.ID,
		&i.AthleteID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Status,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.LastSyncAt,
		&i.LastImportCursor,
		&i.TokenReference,
		&i.TokenExpiresAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProviderConnectionsByAthlete = `-- name: ListProviderConnectionsByAthlete :many
SELECT id, athlete_id, provider, provider_user_id, status, connected_at, disconnected_at, last_sync_at, last_import_cursor, token_reference, token_expires_at, last_error, created_at, updated_at
FROM provider_connections
WHERE athlete_id = $1
ORDER BY created_at DESC, id
`

func (q *Queries) ListProviderConnectionsByAthlete(ctx context.Context, athleteID uuid.UUID) ([]ProviderConnection, error) {
	rows, err := q.db.QueryContext(ctx, listProviderConnectionsByAthlete, athleteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderConnection
	for rows.Next() {
		var i ProviderConnection
		if err := rows.Scan(
			&i.ID,
			&i.AthleteID,
			&i.Provider,
			&i.ProviderUserID,
			&i.Status,
			&i.ConnectedAt,
			&i.DisconnectedAt,
			&i.LastSyncAt,
			&i.LastImportCursor,
			&i.TokenReference,
			&i.TokenExpiresAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderConnectionsByStatus = `-- name: ListProviderConnectionsByStatus :many
SELECT id, athlete_id, provider, provider_user_id, status, connected_at, disconnected_at, last_sync_at, last_import_cursor, token_reference, token_expires_at, last_error, created_at, updated_at
FROM provider_connections
WHERE status = $1
ORDER BY updated_at ASC, id
`

func (q *Queries) ListProviderConnectionsByStatus(ctx context.Context, status string) ([]ProviderConnection, error) {
	rows, err := q.db.QueryContext(ctx, listProviderConnectionsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderConnection
	for rows.Next() {
		var i ProviderConnection
		if err := rows.Scan(
			&i.ID,
			&i.AthleteID,
			&i.Provider,
			&i.ProviderUserID,
			&i.Status,
			&i.ConnectedAt,
			&i.DisconnectedAt,
			&i.LastSyncAt,
			&i.LastImportCursor,
			&i.TokenReference,
			&i.TokenExpiresAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProviderConnection = `-- name: UpdateProviderConnection :one
UPDATE provider_connections
SET
    provider_user_id = $1,
    status = $2,
    connected_at = $3,
    disconnected_at = $4,
    last_sync_at = $5,
    last_import_cursor = $6,
    token_reference = $7,
    token_expires_at = $8,
    last_error = $9,
    updated_at = now()
WHERE id = $10
RETURNING id, athlete_id, provider, provider_user_id, status, connected_at, disconnected_at, last_sync_at, last_import_cursor, token_reference, token_expires_at, last_error, created_at, updated_at
`

type UpdateProviderConnectionParams struct {
	ProviderUserID   sql.NullString `json:"provider_user_id"`
	Status           string         `json:"status"`
	ConnectedAt      sql.NullTime   `json:"connected_at"`
	DisconnectedAt   sql.NullTime   `json:"disconnected_at"`
	LastSyncAt       sql.NullTime   `json:"last_sync_at"`
	LastImportCursor sql.NullString `json:"last_import_cursor"`
	TokenReference   sql.NullString `json:"token_reference"`
	TokenExpiresAt   sql.NullTime   `json:"token_expires_at"`
	LastError        sql.NullString `json:"last_error"`
	ID               uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateProviderConnection(ctx context.Context, arg UpdateProviderConnectionParams) (ProviderConnection, error) {
	row := q.db.QueryRowContext(ctx, updateProviderConnection,
		arg.ProviderUserID,
		arg.Status,
		arg.ConnectedAt,
		arg.DisconnectedAt,
		arg.LastSyncAt,
		arg.LastImportCursor,
		arg.TokenReference,
		arg.TokenExpiresAt,
		arg.LastError,
		arg.ID,
	)
	var i ProviderConnection
	err := row.Scan(
		&i.ID,
		&i.AthleteID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Status,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.LastSyncAt,
		&i.LastImportCursor,
		&i.TokenReference,
		&i.TokenExpiresAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
