// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_import_events.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createProviderImportEvent = `-- name: CreateProviderImportEvent :one
INSERT INTO provider_import_events (
    id,
    provider_connection_id,
    provider_activity_id,
    provider,
    event_type,
    delivery_id,
    status,
    received_at,
    processed_at,
    error
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, provider_connection_id, provider_activity_id, provider, event_type, delivery_id, status, received_at, processed_at, error
`

type CreateProviderImportEventParams struct {
	ID                   uuid.UUID      `json:"id"`
	ProviderConnectionID uuid.NullUUID  `json:"provider_connection_id"`
	ProviderActivityID   uuid.NullUUID  `json:"provider_activity_id"`
	Provider             string         `json:"provider"`
	EventType            string         `json:"event_type"`
	DeliveryID           sql.NullString `json:"delivery_id"`
	Status               string         `json:"status"`
	ReceivedAt           time.Time      `json:"received_at"`
	ProcessedAt          sql.NullTime   `json:"processed_at"`
	Error                sql.NullString `json:"error"`
}

func (q *Queries) CreateProviderImportEvent(ctx context.Context, arg CreateProviderImportEventParams) (ProviderImportEvent, error) {
	row := q.db.QueryRowContext(ctx, createProviderImportEvent,
		arg.ID,
		arg.ProviderConnectionID,
		arg.ProviderActivityID,
		arg.Provider,
		arg.EventType,
		arg.DeliveryID,
		arg.Status,
		arg.ReceivedAt,
		arg.ProcessedAt,
		arg.Error,
	)
	var i ProviderImportEvent
	err := row.Scan(
		&i.ID,
		&i.ProviderConnectionID,
		&i.ProviderActivityID,
		&i.Provider,
		&i.EventType,
		&i.DeliveryID,
		&i.Status,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.Error,
	)
	return i, err
}

const getProviderImportEvent = `-- name: GetProviderImportEvent :one
SELECT id, provider_connection_id, provider_activity_id, provider, event_type, delivery_id, status, received_at, processed_at, error
FROM provider_import_events
WHERE id = $1
`

func (q *Queries) GetProviderImportEvent(ctx context.Context, id uuid.UUID) (ProviderImportEvent, error) {
	row := q.db.QueryRowContext(ctx, getProviderImportEvent, id)
	var i ProviderImportEvent
	err := row.Scan(
		&i.ID,
		&i.ProviderConnectionID,
		&i.ProviderActivityID,
		&i.Provider,
		&i.EventType,
		&i.DeliveryID,
		&i.Status,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.Error,
	)
	return i, err
}

const listProviderImportEventsByConnection = `-- name: ListProviderImportEventsByConnection :many
SELECT id, provider_connection_id, provider_activity_id, provider, event_type, delivery_id, status, received_at, processed_at, error
FROM provider_import_events
WHERE provider_connection_id = $1::uuid
ORDER BY received_at DESC, id
`

func (q *Queries) ListProviderImportEventsByConnection(ctx context.Context, providerConnectionID uuid.UUID) ([]ProviderImportEvent, error) {
	rows, err := q.db.QueryContext(ctx, listProviderImportEventsByConnection, providerConnectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderImportEvent
	for rows.Next() {
		var i ProviderImportEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProviderConnectionID,
			&i.ProviderActivityID,
			&i.Provider,
			&i.EventType,
			&i.DeliveryID,
			&i.Status,
			&i.ReceivedAt,
			&i.ProcessedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderImportEventsByStatus = `-- name: ListProviderImportEventsByStatus :many
SELECT id, provider_connection_id, provider_activity_id, provider, event_type, delivery_id, status, received_at, processed_at, error
FROM provider_import_events
WHERE status = $1
ORDER BY received_at ASC, id
`

func (q *Queries) ListProviderImportEventsByStatus(ctx context.Context, status string) ([]ProviderImportEvent, error) {
	rows, err := q.db.QueryContext(ctx, listProviderImportEventsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderImportEvent
	for rows.Next() {
		var i ProviderImportEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProviderConnectionID,
			&i.ProviderActivityID,
			&i.Provider,
			&i.EventType,
			&i.DeliveryID,
			&i.Status,
			&i.ReceivedAt,
			&i.ProcessedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProviderImportEventStatus = `-- name: UpdateProviderImportEventStatus :one
UPDATE provider_import_events
SET
    status = $1,
    processed_at = $2,
    error = $3
WHERE id = $4
RETURNING id, provider_connection_id, provider_activity_id, provider, event_type, delivery_id, status, received_at, processed_at, error
`

type UpdateProviderImportEventStatusParams struct {
	Status      string         `json:"status"`
	ProcessedAt sql.NullTime   `json:"processed_at"`
	Error       sql.NullString `json:"error"`
	ID          uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateProviderImportEventStatus(ctx context.Context, arg UpdateProviderImportEventStatusParams) (ProviderImportEvent, error) {
	row := q.db.QueryRowContext(ctx, updateProviderImportEventStatus,
		arg.Status,
		arg.ProcessedAt,
		arg.Error,
		arg.ID,
	)
	var i ProviderImportEvent
	err := row.Scan(
		&i.ID,
		&i.ProviderConnectionID,
		&i.ProviderActivityID,
		&i.Provider,
		&i.EventType,
		&i.DeliveryID,
		&i.Status,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.Error,
	)
	return i, err
}
