// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_activities.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createProviderActivity = `-- name: CreateProviderActivity :one
INSERT INTO provider_activities (
    id,
    provider_connection_id,
    athlete_id,
    imported_activity_id,
    provider,
    provider_activity_id,
    provider_activity_type,
    started_at,
    status,
    first_seen_at,
    last_synced_at,
    last_error
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
RETURNING id, provider_connection_id, athlete_id, imported_activity_id, provider, provider_activity_id, provider_activity_type, started_at, status, first_seen_at, last_synced_at, last_error, created_at, updated_at
`

type CreateProviderActivityParams struct {
	ID                   uuid.UUID      `json:"id"`
	ProviderConnectionID uuid.UUID      `json:"provider_connection_id"`
	AthleteID            uuid.UUID      `json:"athlete_id"`
	ImportedActivityID   uuid.NullUUID  `json:"imported_activity_id"`
	Provider             string         `json:"provider"`
	ProviderActivityID   string         `json:"provider_activity_id"`
	ProviderActivityType sql.NullString `json:"provider_activity_type"`
	StartedAt            sql.NullTime   `json:"started_at"`
	Status               string         `json:"status"`
	FirstSeenAt          time.Time      `json:"first_seen_at"`
	LastSyncedAt         sql.NullTime   `json:"last_synced_at"`
	LastError            sql.NullString `json:"last_error"`
}

func (q *Queries) CreateProviderActivity(ctx context.Context, arg CreateProviderActivityParams) (ProviderActivity, error) {
	row := q.db.QueryRowContext(ctx, createProviderActivity,
		arg.ID,
		arg.ProviderConnectionID,
		arg.AthleteID,
		arg.ImportedActivityID,
		arg.Provider,
		arg.ProviderActivityID,
		arg.ProviderActivityType,
		arg.StartedAt,
		arg.Status,
		arg.FirstSeenAt,
		arg.LastSyncedAt,
		arg.LastError,
	)
	var i ProviderActivity
	err := row.Scan(
		&i.ID,
		&i.ProviderConnectionID,
		&i.AthleteID,
		&i.ImportedActivityID,
		&i.Provider,
		&i.ProviderActivityID,
		&i.ProviderActivityType,
		&i.StartedAt,
		&i.Status,
		&i.FirstSeenAt,
		&i.LastSyncedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderActivity = `-- name: GetProviderActivity :one
SELECT id, provider_connection_id, athlete_id, imported_activity_id, provider, provider_activity_id, provider_activity_type, started_at, status, first_seen_at, last_synced_at, last_error, created_at, updated_at
FROM provider_activities
WHERE id = $1
`

func (q *Queries) GetProviderActivity(ctx context.Context, id uuid.UUID) (ProviderActivity, error) {
	row := q.db.QueryRowContext(ctx, getProviderActivity, id)
	var i ProviderActivity
	err := row.Scan(
		&i.ID,
		&i.ProviderConnectionID,
		&i.AthleteID,
		&i.ImportedActivityID,
		&i.Provider,
		&i.ProviderActivityID,
		&i.ProviderActivityType,
		&i.StartedAt,
		&i.Status,
		&i.FirstSeenAt,
		&i.LastSyncedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderActivityByProviderID = `-- name: GetProviderActivityByProviderID :one
SELECT id, provider_connection_id, athlete_id, imported_activity_id, provider, provider_activity_id, provider_activity_type, started_at, status, first_seen_at, last_synced_at, last_error, created_at, updated_at
FROM provider_activities
WHERE provider_connection_id = $1
  AND provider_activity_id = $2
`

type GetProviderActivityByProviderIDParams struct {
	ProviderConnectionID uuid.UUID `json:"provider_connection_id"`
	ProviderActivityID   string    `json:"provider_activity_id"`
}

func (q *Queries) GetProviderActivityByProviderID(ctx context.Context, arg GetProviderActivityByProviderIDParams) (ProviderActivity, error) {
	row := q.db.QueryRowContext(ctx, getProviderActivityByProviderID, arg.ProviderConnectionID, arg.ProviderActivityID)
	var i ProviderActivity
	err := row.Scan(
		&i.ID,
		&i.ProviderConnectionID,
		&i.AthleteID,
		&i.ImportedActivityID,
		&i.Provider,
		&i.ProviderActivityID,
		&i.ProviderActivityType,
		&i.StartedAt,
		&i.Status,
		&i.FirstSeenAt,
		&i.LastSyncedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProviderActivitiesByAthlete = `-- name: ListProviderActivitiesByAthlete :many
SELECT id, provider_connection_id, athlete_id, imported_activity_id, provider, provider_activity_id, provider_activity_type, started_at, status, first_seen_at, last_synced_at, last_error, created_at, updated_at
FROM provider_activities
WHERE athlete_id = $1
ORDER BY started_at DESC NULLS LAST, first_seen_at DESC, id
`

func (q *Queries) ListProviderActivitiesByAthlete(ctx context.Context, athleteID uuid.UUID) ([]ProviderActivity, error) {
	rows, err := q.db.QueryContext(ctx, listProviderActivitiesByAthlete, athleteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderActivity
	for rows.Next() {
		var i ProviderActivity
		if err := rows.Scan(
			&i.ID,
			&i.ProviderConnectionID,
			&i.AthleteID,
			&i.ImportedActivityID,
			&i.Provider,
			&i.ProviderActivityID,
			&i.ProviderActivityType,
			&i.StartedAt,
			&i.Status,
			&i.FirstSeenAt,
			&i.LastSyncedAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderActivitiesByStatus = `-- name: ListProviderActivitiesByStatus :many
SELECT id, provider_connection_id, athlete_id, imported_activity_id, provider, provider_activity_id, provider_activity_type, started_at, status, first_seen_at, last_synced_at, last_error, created_at, updated_at
FROM provider_activities
WHERE status = $1
ORDER BY first_seen_at ASC, id
`

func (q *Queries) ListProviderActivitiesByStatus(ctx context.Context, status string) ([]ProviderActivity, error) {
	rows, err := q.db.QueryContext(ctx, listProviderActivitiesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderActivity
	for rows.Next() {
		var i ProviderActivity
		if err := rows.Scan(
			&i.ID,
			&i.ProviderConnectionID,
			&i.AthleteID,
			&i.ImportedActivityID,
			&i.Provider,
			&i.ProviderActivityID,
			&i.ProviderActivityType,
			&i.StartedAt,
			&i.Status,
			&i.FirstSeenAt,
			&i.LastSyncedAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProviderActivity = `-- name: UpdateProviderActivity :one
UPDATE provider_activities
SET
    imported_activity_id = $1,
    provider_activity_type = $2,
    started_at = $3,
    status = $4,
    last_synced_at = $5,
    last_error = $6,
    updated_at = now()
WHERE id = $7
RETURNING id, provider_connection_id, athlete_id, imported_activity_id, provider, provider_activity_id, provider_activity_type, started_at, status, first_seen_at, last_synced_at, last_error, created_at, updated_at
`

type UpdateProviderActivityParams struct {
	ImportedActivityID   uuid.NullUUID  `json:"imported_activity_id"`
	ProviderActivityType sql.NullString `json:"provider_activity_type"`
	StartedAt            sql.NullTime   `json:"started_at"`
	Status               string         `json:"status"`
	LastSyncedAt         sql.NullTime   `json:"last_synced_at"`
	LastError            sql.NullString `json:"last_error"`
	ID                   uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateProviderActivity(ctx context.Context, arg UpdateProviderActivityParams) (ProviderActivity, error) {
	row := q.db.QueryRowContext(ctx, updateProviderActivity,
		arg.ImportedActivityID,
		arg.ProviderActivityType,
		arg.StartedAt,
		arg.Status,
		arg.LastSyncedAt,
		arg.LastError,
		arg.ID,
	)
	var i ProviderActivity
	err := row.Scan(
		&i.ID,
		&i.ProviderConnectionID,
		&i.AthleteID,
		&i.ImportedActivityID,
		&i.Provider,
		&i.ProviderActivityID,
		&i.ProviderActivityType,
		&i.StartedAt,
		&i.Status,
		&i.FirstSeenAt,
		&i.LastSyncedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
