// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAdaptationEvent(ctx context.Context, arg CreateAdaptationEventParams) (AdaptationEvent, error)
	CreateAdaptationEventChange(ctx context.Context, arg CreateAdaptationEventChangeParams) (AdaptationEventChange, error)
	CreateAthleteProfile(ctx context.Context, arg CreateAthleteProfileParams) (AthleteProfile, error)
	CreateImportedActivity(ctx context.Context, arg CreateImportedActivityParams) (ImportedActivity, error)
	CreatePlanWeek(ctx context.Context, arg CreatePlanWeekParams) (PlanWeek, error)
	CreatePlannedWorkout(ctx context.Context, arg CreatePlannedWorkoutParams) (PlannedWorkout, error)
	CreateProviderActivity(ctx context.Context, arg CreateProviderActivityParams) (ProviderActivity, error)
	CreateProviderActivityPayload(ctx context.Context, arg CreateProviderActivityPayloadParams) (ProviderActivityPayload, error)
	CreateProviderConnection(ctx context.Context, arg CreateProviderConnectionParams) (ProviderConnection, error)
	CreateProviderImportEvent(ctx context.Context, arg CreateProviderImportEventParams) (ProviderImportEvent, error)
	CreateTrainingGoal(ctx context.Context, arg CreateTrainingGoalParams) (TrainingGoal, error)
	CreateWorkoutMatch(ctx context.Context, arg CreateWorkoutMatchParams) (WorkoutMatch, error)
	CreateWorkoutResult(ctx context.Context, arg CreateWorkoutResultParams) (WorkoutResult, error)
	DeleteAdaptationEvent(ctx context.Context, id uuid.UUID) error
	DeleteAdaptationEventChanges(ctx context.Context, adaptationEventID uuid.UUID) error
	DeleteAthleteProfile(ctx context.Context, id uuid.UUID) error
	DeleteImportedActivity(ctx context.Context, id uuid.UUID) error
	DeletePlanWeek(ctx context.Context, id uuid.UUID) error
	DeletePlannedWorkout(ctx context.Context, id uuid.UUID) error
	DeleteTrainingGoal(ctx context.Context, id uuid.UUID) error
	DeleteWorkoutMatch(ctx context.Context, id uuid.UUID) error
	DeleteWorkoutResult(ctx context.Context, id uuid.UUID) error
	GetAdaptationEvent(ctx context.Context, id uuid.UUID) (AdaptationEvent, error)
	GetAthleteProfile(ctx context.Context, id uuid.UUID) (AthleteProfile, error)
	GetImportedActivity(ctx context.Context, id uuid.UUID) (ImportedActivity, error)
	GetPlanWeek(ctx context.Context, id uuid.UUID) (PlanWeek, error)
	GetPlannedWorkout(ctx context.Context, id uuid.UUID) (PlannedWorkout, error)
	GetProviderActivity(ctx context.Context, id uuid.UUID) (ProviderActivity, error)
	GetProviderActivityByProviderID(ctx context.Context, arg GetProviderActivityByProviderIDParams) (ProviderActivity, error)
	GetProviderActivityPayload(ctx context.Context, id uuid.UUID) (ProviderActivityPayload, error)
	GetProviderConnection(ctx context.Context, id uuid.UUID) (ProviderConnection, error)
	GetProviderImportEvent(ctx context.Context, id uuid.UUID) (ProviderImportEvent, error)
	GetTrainingGoal(ctx context.Context, id uuid.UUID) (TrainingGoal, error)
	GetWorkoutMatch(ctx context.Context, id uuid.UUID) (WorkoutMatch, error)
	GetWorkoutResult(ctx context.Context, id uuid.UUID) (WorkoutResult, error)
	ListAdaptationEventChanges(ctx context.Context, adaptationEventID uuid.UUID) ([]AdaptationEventChange, error)
	ListAdaptationEventsByAthlete(ctx context.Context, athleteID uuid.UUID) ([]AdaptationEvent, error)
	ListAdaptationEventsByPlan(ctx context.Context, planID uuid.UUID) ([]AdaptationEvent, error)
	ListImportedActivitiesByAthlete(ctx context.Context, athleteID uuid.UUID) ([]ImportedActivity, error)
	ListPlanWeeksByAthlete(ctx context.Context, athleteID uuid.UUID) ([]PlanWeek, error)
	ListPlanWeeksByPlan(ctx context.Context, planID uuid.UUID) ([]PlanWeek, error)
	ListPlannedWorkoutsByPlan(ctx context.Context, planID uuid.UUID) ([]PlannedWorkout, error)
	ListPlannedWorkoutsByWeek(ctx context.Context, planWeekID uuid.UUID) ([]PlannedWorkout, error)
	ListProviderActivitiesByAthlete(ctx context.Context, athleteID uuid.UUID) ([]ProviderActivity, error)
	ListProviderActivitiesByStatus(ctx context.Context, status string) ([]ProviderActivity, error)
	ListProviderActivityPayloads(ctx context.Context, providerActivityID uuid.UUID) ([]ProviderActivityPayload, error)
	ListProviderConnectionsByAthlete(ctx context.Context, athleteID uuid.UUID) ([]ProviderConnection, error)
	ListProviderConnectionsByStatus(ctx context.Context, status string) ([]ProviderConnection, error)
	ListProviderImportEventsByConnection(ctx context.Context, providerConnectionID uuid.UUID) ([]ProviderImportEvent, error)
	ListProviderImportEventsByStatus(ctx context.Context, status string) ([]ProviderImportEvent, error)
	ListTrainingGoalsByAthlete(ctx context.Context, athleteID uuid.UUID) ([]TrainingGoal, error)
	ListWorkoutMatchesByImportedActivity(ctx context.Context, importedActivityID uuid.UUID) ([]WorkoutMatch, error)
	ListWorkoutMatchesByPlannedWorkout(ctx context.Context, plannedWorkoutID uuid.UUID) ([]WorkoutMatch, error)
	ListWorkoutResultsByImportedActivity(ctx context.Context, importedActivityID uuid.NullUUID) ([]WorkoutResult, error)
	ListWorkoutResultsByPlannedWorkout(ctx context.Context, plannedWorkoutID uuid.UUID) ([]WorkoutResult, error)
	UpdateAdaptationEvent(ctx context.Context, arg UpdateAdaptationEventParams) (AdaptationEvent, error)
	UpdateAthleteProfile(ctx context.Context, arg UpdateAthleteProfileParams) (AthleteProfile, error)
	UpdateImportedActivity(ctx context.Context, arg UpdateImportedActivityParams) (ImportedActivity, error)
	UpdatePlanWeek(ctx context.Context, arg UpdatePlanWeekParams) (PlanWeek, error)
	UpdatePlannedWorkout(ctx context.Context, arg UpdatePlannedWorkoutParams) (PlannedWorkout, error)
	UpdatePlannedWorkoutStatus(ctx context.Context, arg UpdatePlannedWorkoutStatusParams) (PlannedWorkout, error)
	UpdateProviderActivity(ctx context.Context, arg UpdateProviderActivityParams) (ProviderActivity, error)
	UpdateProviderActivityPayload(ctx context.Context, arg UpdateProviderActivityPayloadParams) (ProviderActivityPayload, error)
	UpdateProviderConnection(ctx context.Context, arg UpdateProviderConnectionParams) (ProviderConnection, error)
	UpdateProviderImportEventStatus(ctx context.Context, arg UpdateProviderImportEventStatusParams) (ProviderImportEvent, error)
	UpdateTrainingGoal(ctx context.Context, arg UpdateTrainingGoalParams) (TrainingGoal, error)
	UpdateWorkoutMatch(ctx context.Context, arg UpdateWorkoutMatchParams) (WorkoutMatch, error)
	UpdateWorkoutResult(ctx context.Context, arg UpdateWorkoutResultParams) (WorkoutResult, error)
}

var _ Querier = (*Queries)(nil)
