// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: training_goals.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createTrainingGoal = `-- name: CreateTrainingGoal :one
INSERT INTO training_goals (
    id,
    athlete_id,
    type,
    target_date,
    target_distance_meters,
    target_duration_seconds,
    notes
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, athlete_id, type, target_date, target_distance_meters, target_duration_seconds, notes, created_at, updated_at
`

type CreateTrainingGoalParams struct {
	ID                    uuid.UUID       `json:"id"`
	AthleteID             uuid.UUID       `json:"athlete_id"`
	Type                  string          `json:"type"`
	TargetDate            sql.NullTime    `json:"target_date"`
	TargetDistanceMeters  sql.NullFloat64 `json:"target_distance_meters"`
	TargetDurationSeconds sql.NullInt32   `json:"target_duration_seconds"`
	Notes                 sql.NullString  `json:"notes"`
}

func (q *Queries) CreateTrainingGoal(ctx context.Context, arg CreateTrainingGoalParams) (TrainingGoal, error) {
	row := q.db.QueryRowContext(ctx, createTrainingGoal,
		arg.ID,
		arg.AthleteID,
		arg.Type,
		arg.TargetDate,
		arg.TargetDistanceMeters,
		arg.TargetDurationSeconds,
		arg.Notes,
	)
	var i TrainingGoal
	err := row.Scan(
		&i.ID,
		&i.AthleteID,
		&i.Type,
		&i.TargetDate,
		&i.TargetDistanceMeters,
		&i.TargetDurationSeconds,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTrainingGoal = `-- name: DeleteTrainingGoal :exec
DELETE FROM training_goals
WHERE id = $1
`

func (q *Queries) DeleteTrainingGoal(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTrainingGoal, id)
	return err
}

const getTrainingGoal = `-- name: GetTrainingGoal :one
SELECT id, athlete_id, type, target_date, target_distance_meters, target_duration_seconds, notes, created_at, updated_at
FROM training_goals
WHERE id = $1
`

func (q *Queries) GetTrainingGoal(ctx context.Context, id uuid.UUID) (TrainingGoal, error) {
	row := q.db.QueryRowContext(ctx, getTrainingGoal, id)
	var i TrainingGoal
	err := row.Scan(
		&i.ID,
		&i.AthleteID,
		&i.Type,
		&i.TargetDate,
		&i.TargetDistanceMeters,
		&i.TargetDurationSeconds,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTrainingGoalsByAthlete = `-- name: ListTrainingGoalsByAthlete :many
SELECT id, athlete_id, type, target_date, target_distance_meters, target_duration_seconds, notes, created_at, updated_at
FROM training_goals
WHERE athlete_id = $1
ORDER BY created_at DESC, id
`

func (q *Queries) ListTrainingGoalsByAthlete(ctx context.Context, athleteID uuid.UUID) ([]TrainingGoal, error) {
	rows, err := q.db.QueryContext(ctx, listTrainingGoalsByAthlete, athleteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrainingGoal
	for rows.Next() {
		var i TrainingGoal
		if err := rows.Scan(
			&i.ID,
			&i.AthleteID,
			&i.Type,
			&i.TargetDate,
			&i.TargetDistanceMeters,
			&i.TargetDurationSeconds,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTrainingGoal = `-- name: UpdateTrainingGoal :one
UPDATE training_goals
SET
    type = $1,
    target_date = $2,
    target_distance_meters = $3,
    target_duration_seconds = $4,
    notes = $5,
    updated_at = now()
WHERE id = $6
RETURNING id, athlete_id, type, target_date, target_distance_meters, target_duration_seconds, notes, created_at, updated_at
`

type UpdateTrainingGoalParams struct {
	Type                  string          `json:"type"`
	TargetDate            sql.NullTime    `json:"target_date"`
	TargetDistanceMeters  sql.NullFloat64 `json:"target_distance_meters"`
	TargetDurationSeconds sql.NullInt32   `json:"target_duration_seconds"`
	Notes                 sql.NullString  `json:"notes"`
	ID                    uuid.UUID       `json:"id"`
}

func (q *Queries) UpdateTrainingGoal(ctx context.Context, arg UpdateTrainingGoalParams) (TrainingGoal, error) {
	row := q.db.QueryRowContext(ctx, updateTrainingGoal,
		arg.Type,
		arg.TargetDate,
		arg.TargetDistanceMeters,
		arg.TargetDurationSeconds,
		arg.Notes,
		arg.ID,
	)
	var i TrainingGoal
	err := row.Scan(
		&i.ID,
		&i.AthleteID,
		&i.Type,
		&i.TargetDate,
		&i.TargetDistanceMeters,
		&i.TargetDurationSeconds,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
