// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workout_matches.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createWorkoutMatch = `-- name: CreateWorkoutMatch :one
INSERT INTO workout_matches (
    id,
    planned_workout_id,
    imported_activity_id,
    status,
    confidence,
    matched_by,
    matched_at,
    notes
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, planned_workout_id, imported_activity_id, status, confidence, matched_by, matched_at, notes, created_at
`

type CreateWorkoutMatchParams struct {
	ID                 uuid.UUID      `json:"id"`
	PlannedWorkoutID   uuid.UUID      `json:"planned_workout_id"`
	ImportedActivityID uuid.UUID      `json:"imported_activity_id"`
	Status             string         `json:"status"`
	Confidence         string         `json:"confidence"`
	MatchedBy          string         `json:"matched_by"`
	MatchedAt          time.Time      `json:"matched_at"`
	Notes              sql.NullString `json:"notes"`
}

func (q *Queries) CreateWorkoutMatch(ctx context.Context, arg CreateWorkoutMatchParams) (WorkoutMatch, error) {
	row := q.db.QueryRowContext(ctx, createWorkoutMatch,
		arg.ID,
		arg.PlannedWorkoutID,
		arg.ImportedActivityID,
		arg.Status,
		arg.Confidence,
		arg.MatchedBy,
		arg.MatchedAt,
		arg.Notes,
	)
	var i WorkoutMatch
	err := row.Scan(
		&i.ID,
		&i.PlannedWorkoutID,
		&i.ImportedActivityID,
		&i.Status,
		&i.Confidence,
		&i.MatchedBy,
		&i.MatchedAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWorkoutMatch = `-- name: DeleteWorkoutMatch :exec
DELETE FROM workout_matches
WHERE id = $1
`

func (q *Queries) DeleteWorkoutMatch(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteWorkoutMatch, id)
	return err
}

const getWorkoutMatch = `-- name: GetWorkoutMatch :one
SELECT id, planned_workout_id, imported_activity_id, status, confidence, matched_by, matched_at, notes, created_at
FROM workout_matches
WHERE id = $1
`

func (q *Queries) GetWorkoutMatch(ctx context.Context, id uuid.UUID) (WorkoutMatch, error) {
	row := q.db.QueryRowContext(ctx, getWorkoutMatch, id)
	var i WorkoutMatch
	err := row.Scan(
		&i.ID,
		&i.PlannedWorkoutID,
		&i.ImportedActivityID,
		&i.Status,
		&i.Confidence,
		&i.MatchedBy,
		&i.MatchedAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listWorkoutMatchesByImportedActivity = `-- name: ListWorkoutMatchesByImportedActivity :many
SELECT id, planned_workout_id, imported_activity_id, status, confidence, matched_by, matched_at, notes, created_at
FROM workout_matches
WHERE imported_activity_id = $1
ORDER BY matched_at DESC, id
`

func (q *Queries) ListWorkoutMatchesByImportedActivity(ctx context.Context, importedActivityID uuid.UUID) ([]WorkoutMatch, error) {
	rows, err := q.db.QueryContext(ctx, listWorkoutMatchesByImportedActivity, importedActivityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkoutMatch
	for rows.Next() {
		var i WorkoutMatch
		if err := rows.Scan(
			&i.ID,
			&i.PlannedWorkoutID,
			&i.ImportedActivityID,
			&i.Status,
			&i.Confidence,
			&i.MatchedBy,
			&i.MatchedAt,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutMatchesByPlannedWorkout = `-- name: ListWorkoutMatchesByPlannedWorkout :many
SELECT id, planned_workout_id, imported_activity_id, status, confidence, matched_by, matched_at, notes, created_at
FROM workout_matches
WHERE planned_workout_id = $1
ORDER BY matched_at DESC, id
`

func (q *Queries) ListWorkoutMatchesByPlannedWorkout(ctx context.Context, plannedWorkoutID uuid.UUID) ([]WorkoutMatch, error) {
	rows, err := q.db.QueryContext(ctx, listWorkoutMatchesByPlannedWorkout, plannedWorkoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkoutMatch
	for rows.Next() {
		var i WorkoutMatch
		if err := rows.Scan(
			&i.ID,
			&i.PlannedWorkoutID,
			&i.ImportedActivityID,
			&i.Status,
			&i.Confidence,
			&i.MatchedBy,
			&i.MatchedAt,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkoutMatch = `-- name: UpdateWorkoutMatch :one
UPDATE workout_matches
SET
    planned_workout_id = $1,
    imported_activity_id = $2,
    status = $3,
    confidence = $4,
    matched_by = $5,
    matched_at = $6,
    notes = $7
WHERE id = $8
RETURNING id, planned_workout_id, imported_activity_id, status, confidence, matched_by, matched_at, notes, created_at
`

type UpdateWorkoutMatchParams struct {
	PlannedWorkoutID   uuid.UUID      `json:"planned_workout_id"`
	ImportedActivityID uuid.UUID      `json:"imported_activity_id"`
	Status             string         `json:"status"`
	Confidence         string         `json:"confidence"`
	MatchedBy          string         `json:"matched_by"`
	MatchedAt          time.Time      `json:"matched_at"`
	Notes              sql.NullString `json:"notes"`
	ID                 uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateWorkoutMatch(ctx context.Context, arg UpdateWorkoutMatchParams) (WorkoutMatch, error) {
	row := q.db.QueryRowContext(ctx, updateWorkoutMatch,
		arg.PlannedWorkoutID,
		arg.ImportedActivityID,
		arg.Status,
		arg.Confidence,
		arg.MatchedBy,
		arg.MatchedAt,
		arg.Notes,
		arg.ID,
	)
	var i WorkoutMatch
	err := row.Scan(
		&i.ID,
		&i.PlannedWorkoutID,
		&i.ImportedActivityID,
		&i.Status,
		&i.Confidence,
		&i.MatchedBy,
		&i.MatchedAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
