// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: runthread/v1/runthread.proto

package runthreadv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/runthread/runthread/services/api/internal/rpc/runthread/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RunthreadServiceName is the fully-qualified name of the RunthreadService service.
	RunthreadServiceName = "runthread.v1.RunthreadService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RunthreadServiceGetCurrentPlanWeekProcedure is the fully-qualified name of the RunthreadService's
	// GetCurrentPlanWeek RPC.
	RunthreadServiceGetCurrentPlanWeekProcedure = "/runthread.v1.RunthreadService/GetCurrentPlanWeek"
	// RunthreadServiceGetProviderConnectionStatusProcedure is the fully-qualified name of the
	// RunthreadService's GetProviderConnectionStatus RPC.
	RunthreadServiceGetProviderConnectionStatusProcedure = "/runthread.v1.RunthreadService/GetProviderConnectionStatus"
	// RunthreadServiceStartProviderConnectionProcedure is the fully-qualified name of the
	// RunthreadService's StartProviderConnection RPC.
	RunthreadServiceStartProviderConnectionProcedure = "/runthread.v1.RunthreadService/StartProviderConnection"
	// RunthreadServiceCompleteImportedActivityProcedure is the fully-qualified name of the
	// RunthreadService's CompleteImportedActivity RPC.
	RunthreadServiceCompleteImportedActivityProcedure = "/runthread.v1.RunthreadService/CompleteImportedActivity"
)

// RunthreadServiceClient is a client for the runthread.v1.RunthreadService service.
type RunthreadServiceClient interface {
	GetCurrentPlanWeek(context.Context, *connect.Request[v1.GetCurrentPlanWeekRequest]) (*connect.Response[v1.GetCurrentPlanWeekResponse], error)
	GetProviderConnectionStatus(context.Context, *connect.Request[v1.GetProviderConnectionStatusRequest]) (*connect.Response[v1.GetProviderConnectionStatusResponse], error)
	StartProviderConnection(context.Context, *connect.Request[v1.StartProviderConnectionRequest]) (*connect.Response[v1.StartProviderConnectionResponse], error)
	CompleteImportedActivity(context.Context, *connect.Request[v1.CompleteImportedActivityRequest]) (*connect.Response[v1.CompleteImportedActivityResponse], error)
}

// NewRunthreadServiceClient constructs a client for the runthread.v1.RunthreadService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRunthreadServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RunthreadServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	runthreadServiceMethods := v1.File_runthread_v1_runthread_proto.Services().ByName("RunthreadService").Methods()
	return &runthreadServiceClient{
		getCurrentPlanWeek: connect.NewClient[v1.GetCurrentPlanWeekRequest, v1.GetCurrentPlanWeekResponse](
			httpClient,
			baseURL+RunthreadServiceGetCurrentPlanWeekProcedure,
			connect.WithSchema(runthreadServiceMethods.ByName("GetCurrentPlanWeek")),
			connect.WithClientOptions(opts...),
		),
		getProviderConnectionStatus: connect.NewClient[v1.GetProviderConnectionStatusRequest, v1.GetProviderConnectionStatusResponse](
			httpClient,
			baseURL+RunthreadServiceGetProviderConnectionStatusProcedure,
			connect.WithSchema(runthreadServiceMethods.ByName("GetProviderConnectionStatus")),
			connect.WithClientOptions(opts...),
		),
		startProviderConnection: connect.NewClient[v1.StartProviderConnectionRequest, v1.StartProviderConnectionResponse](
			httpClient,
			baseURL+RunthreadServiceStartProviderConnectionProcedure,
			connect.WithSchema(runthreadServiceMethods.ByName("StartProviderConnection")),
			connect.WithClientOptions(opts...),
		),
		completeImportedActivity: connect.NewClient[v1.CompleteImportedActivityRequest, v1.CompleteImportedActivityResponse](
			httpClient,
			baseURL+RunthreadServiceCompleteImportedActivityProcedure,
			connect.WithSchema(runthreadServiceMethods.ByName("CompleteImportedActivity")),
			connect.WithClientOptions(opts...),
		),
	}
}

// runthreadServiceClient implements RunthreadServiceClient.
type runthreadServiceClient struct {
	getCurrentPlanWeek          *connect.Client[v1.GetCurrentPlanWeekRequest, v1.GetCurrentPlanWeekResponse]
	getProviderConnectionStatus *connect.Client[v1.GetProviderConnectionStatusRequest, v1.GetProviderConnectionStatusResponse]
	startProviderConnection     *connect.Client[v1.StartProviderConnectionRequest, v1.StartProviderConnectionResponse]
	completeImportedActivity    *connect.Client[v1.CompleteImportedActivityRequest, v1.CompleteImportedActivityResponse]
}

// GetCurrentPlanWeek calls runthread.v1.RunthreadService.GetCurrentPlanWeek.
func (c *runthreadServiceClient) GetCurrentPlanWeek(ctx context.Context, req *connect.Request[v1.GetCurrentPlanWeekRequest]) (*connect.Response[v1.GetCurrentPlanWeekResponse], error) {
	return c.getCurrentPlanWeek.CallUnary(ctx, req)
}

// GetProviderConnectionStatus calls runthread.v1.RunthreadService.GetProviderConnectionStatus.
func (c *runthreadServiceClient) GetProviderConnectionStatus(ctx context.Context, req *connect.Request[v1.GetProviderConnectionStatusRequest]) (*connect.Response[v1.GetProviderConnectionStatusResponse], error) {
	return c.getProviderConnectionStatus.CallUnary(ctx, req)
}

// StartProviderConnection calls runthread.v1.RunthreadService.StartProviderConnection.
func (c *runthreadServiceClient) StartProviderConnection(ctx context.Context, req *connect.Request[v1.StartProviderConnectionRequest]) (*connect.Response[v1.StartProviderConnectionResponse], error) {
	return c.startProviderConnection.CallUnary(ctx, req)
}

// CompleteImportedActivity calls runthread.v1.RunthreadService.CompleteImportedActivity.
func (c *runthreadServiceClient) CompleteImportedActivity(ctx context.Context, req *connect.Request[v1.CompleteImportedActivityRequest]) (*connect.Response[v1.CompleteImportedActivityResponse], error) {
	return c.completeImportedActivity.CallUnary(ctx, req)
}

// RunthreadServiceHandler is an implementation of the runthread.v1.RunthreadService service.
type RunthreadServiceHandler interface {
	GetCurrentPlanWeek(context.Context, *connect.Request[v1.GetCurrentPlanWeekRequest]) (*connect.Response[v1.GetCurrentPlanWeekResponse], error)
	GetProviderConnectionStatus(context.Context, *connect.Request[v1.GetProviderConnectionStatusRequest]) (*connect.Response[v1.GetProviderConnectionStatusResponse], error)
	StartProviderConnection(context.Context, *connect.Request[v1.StartProviderConnectionRequest]) (*connect.Response[v1.StartProviderConnectionResponse], error)
	CompleteImportedActivity(context.Context, *connect.Request[v1.CompleteImportedActivityRequest]) (*connect.Response[v1.CompleteImportedActivityResponse], error)
}

// NewRunthreadServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRunthreadServiceHandler(svc RunthreadServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	runthreadServiceMethods := v1.File_runthread_v1_runthread_proto.Services().ByName("RunthreadService").Methods()
	runthreadServiceGetCurrentPlanWeekHandler := connect.NewUnaryHandler(
		RunthreadServiceGetCurrentPlanWeekProcedure,
		svc.GetCurrentPlanWeek,
		connect.WithSchema(runthreadServiceMethods.ByName("GetCurrentPlanWeek")),
		connect.WithHandlerOptions(opts...),
	)
	runthreadServiceGetProviderConnectionStatusHandler := connect.NewUnaryHandler(
		RunthreadServiceGetProviderConnectionStatusProcedure,
		svc.GetProviderConnectionStatus,
		connect.WithSchema(runthreadServiceMethods.ByName("GetProviderConnectionStatus")),
		connect.WithHandlerOptions(opts...),
	)
	runthreadServiceStartProviderConnectionHandler := connect.NewUnaryHandler(
		RunthreadServiceStartProviderConnectionProcedure,
		svc.StartProviderConnection,
		connect.WithSchema(runthreadServiceMethods.ByName("StartProviderConnection")),
		connect.WithHandlerOptions(opts...),
	)
	runthreadServiceCompleteImportedActivityHandler := connect.NewUnaryHandler(
		RunthreadServiceCompleteImportedActivityProcedure,
		svc.CompleteImportedActivity,
		connect.WithSchema(runthreadServiceMethods.ByName("CompleteImportedActivity")),
		connect.WithHandlerOptions(opts...),
	)
	return "/runthread.v1.RunthreadService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RunthreadServiceGetCurrentPlanWeekProcedure:
			runthreadServiceGetCurrentPlanWeekHandler.ServeHTTP(w, r)
		case RunthreadServiceGetProviderConnectionStatusProcedure:
			runthreadServiceGetProviderConnectionStatusHandler.ServeHTTP(w, r)
		case RunthreadServiceStartProviderConnectionProcedure:
			runthreadServiceStartProviderConnectionHandler.ServeHTTP(w, r)
		case RunthreadServiceCompleteImportedActivityProcedure:
			runthreadServiceCompleteImportedActivityHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRunthreadServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRunthreadServiceHandler struct{}

func (UnimplementedRunthreadServiceHandler) GetCurrentPlanWeek(context.Context, *connect.Request[v1.GetCurrentPlanWeekRequest]) (*connect.Response[v1.GetCurrentPlanWeekResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runthread.v1.RunthreadService.GetCurrentPlanWeek is not implemented"))
}

func (UnimplementedRunthreadServiceHandler) GetProviderConnectionStatus(context.Context, *connect.Request[v1.GetProviderConnectionStatusRequest]) (*connect.Response[v1.GetProviderConnectionStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runthread.v1.RunthreadService.GetProviderConnectionStatus is not implemented"))
}

func (UnimplementedRunthreadServiceHandler) StartProviderConnection(context.Context, *connect.Request[v1.StartProviderConnectionRequest]) (*connect.Response[v1.StartProviderConnectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runthread.v1.RunthreadService.StartProviderConnection is not implemented"))
}

func (UnimplementedRunthreadServiceHandler) CompleteImportedActivity(context.Context, *connect.Request[v1.CompleteImportedActivityRequest]) (*connect.Response[v1.CompleteImportedActivityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runthread.v1.RunthreadService.CompleteImportedActivity is not implemented"))
}
